// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getComicDetail = `-- name: GetComicDetail :one
SELECT comics.id, comics.library_id, comics.series_id, comics.object_key, comics.file_size, comics.file_etag, comics.content_hash, comics.format, comics.title, comics.number, comics.number_sort, comics.volume, comics.summary, comics.released_at, comics.age_rating, comics.language, comics.page_count, comics.cover_page, comics.state, comics.state_detail, comics.hydrated_at, comics.indexed_at, comics.metadata, comics.locked_fields, comics.created_at, comics.updated_at, comics.deleted_at, comics.search_vector, series.id, series.library_id, series.name, series.sort_name, series.description, series.publisher, series.status, series.age_rating, series.year_started, series.cover_comic_id, series.comic_count, series.metadata, series.locked_fields, series.created_at, series.updated_at
FROM comics
LEFT JOIN series ON series.id = comics.series_id
WHERE comics.id = $1 AND comics.deleted_at IS NULL
`

type GetComicDetailRow struct {
	Comic  Comic
	Series Series
}

func (q *Queries) GetComicDetail(ctx context.Context, id uuid.UUID) (GetComicDetailRow, error) {
	row := q.db.QueryRow(ctx, getComicDetail, id)
	var i GetComicDetailRow
	err := row.Scan(
		&i.Comic.ID,
		&i.Comic.LibraryID,
		&i.Comic.SeriesID,
		&i.Comic.ObjectKey,
		&i.Comic.FileSize,
		&i.Comic.FileEtag,
		&i.Comic.ContentHash,
		&i.Comic.Format,
		&i.Comic.Title,
		&i.Comic.Number,
		&i.Comic.NumberSort,
		&i.Comic.Volume,
		&i.Comic.Summary,
		&i.Comic.ReleasedAt,
		&i.Comic.AgeRating,
		&i.Comic.Language,
		&i.Comic.PageCount,
		&i.Comic.CoverPage,
		&i.Comic.State,
		&i.Comic.StateDetail,
		&i.Comic.HydratedAt,
		&i.Comic.IndexedAt,
		&i.Comic.Metadata,
		&i.Comic.LockedFields,
		&i.Comic.CreatedAt,
		&i.Comic.UpdatedAt,
		&i.Comic.DeletedAt,
		&i.Comic.SearchVector,
		&i.Series.ID,
		&i.Series.LibraryID,
		&i.Series.Name,
		&i.Series.SortName,
		&i.Series.Description,
		&i.Series.Publisher,
		&i.Series.Status,
		&i.Series.AgeRating,
		&i.Series.YearStarted,
		&i.Series.CoverComicID,
		&i.Series.ComicCount,
		&i.Series.Metadata,
		&i.Series.LockedFields,
		&i.Series.CreatedAt,
		&i.Series.UpdatedAt,
	)
	return i, err
}

const listComicsBySeries = `-- name: ListComicsBySeries :many
SELECT id, library_id, series_id, object_key, file_size, file_etag, content_hash, format, title, number, number_sort, volume, summary, released_at, age_rating, language, page_count, cover_page, state, state_detail, hydrated_at, indexed_at, metadata, locked_fields, created_at, updated_at, deleted_at, search_vector FROM comics
WHERE series_id = $1 AND deleted_at IS NULL
ORDER BY number_sort NULLS LAST, title
`

func (q *Queries) ListComicsBySeries(ctx context.Context, seriesID uuid.NullUUID) ([]Comic, error) {
	rows, err := q.db.Query(ctx, listComicsBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comic{}
	for rows.Next() {
		var i Comic
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.SeriesID,
			&i.ObjectKey,
			&i.FileSize,
			&i.FileEtag,
			&i.ContentHash,
			&i.Format,
			&i.Title,
			&i.Number,
			&i.NumberSort,
			&i.Volume,
			&i.Summary,
			&i.ReleasedAt,
			&i.AgeRating,
			&i.Language,
			&i.PageCount,
			&i.CoverPage,
			&i.State,
			&i.StateDetail,
			&i.HydratedAt,
			&i.IndexedAt,
			&i.Metadata,
			&i.LockedFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComicsPage = `-- name: ListComicsPage :many

SELECT id, library_id, series_id, object_key, file_size, file_etag, content_hash, format, title, number, number_sort, volume, summary, released_at, age_rating, language, page_count, cover_page, state, state_detail, hydrated_at, indexed_at, metadata, locked_fields, created_at, updated_at, deleted_at, search_vector FROM comics
WHERE library_id = ANY($1::uuid[])
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR series_id = $2::uuid)
  AND ($3::text = '' OR state::text = $3)
  -- Filtrage par classification d'âge, pour les profils restreints.
  AND ($4::smallint IS NULL
       OR age_rating IS NULL
       OR age_rating <= $4::smallint)
  -- Curseur : (created_at, id) est un ordre total, donc sans ex æquo ambigus.
  AND ($5::timestamptz IS NULL
       OR (created_at, id) < ($5::timestamptz, $6::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $7
`

type ListComicsPageParams struct {
	LibraryIds      []uuid.UUID
	SeriesID        uuid.NullUUID
	State           string
	MaxAgeRating    *int16
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.NullUUID
	PageSize        int32
}

// Requêtes de consultation du catalogue.
//
// Pagination par curseur plutôt que par OFFSET : sur une bibliothèque de
// plusieurs milliers de titres, OFFSET force PostgreSQL à parcourir puis jeter
// toutes les lignes précédentes, et une insertion pendant la pagination décale
// silencieusement les résultats. Le curseur est stable et à coût constant.
func (q *Queries) ListComicsPage(ctx context.Context, arg ListComicsPageParams) ([]Comic, error) {
	rows, err := q.db.Query(ctx, listComicsPage,
		arg.LibraryIds,
		arg.SeriesID,
		arg.State,
		arg.MaxAgeRating,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comic{}
	for rows.Next() {
		var i Comic
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.SeriesID,
			&i.ObjectKey,
			&i.FileSize,
			&i.FileEtag,
			&i.ContentHash,
			&i.Format,
			&i.Title,
			&i.Number,
			&i.NumberSort,
			&i.Volume,
			&i.Summary,
			&i.ReleasedAt,
			&i.AgeRating,
			&i.Language,
			&i.PageCount,
			&i.CoverPage,
			&i.State,
			&i.StateDetail,
			&i.HydratedAt,
			&i.IndexedAt,
			&i.Metadata,
			&i.LockedFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNextInSeries = `-- name: ListNextInSeries :many
SELECT DISTINCT ON (c.series_id) c.id, c.library_id, c.series_id, c.object_key, c.file_size, c.file_etag, c.content_hash, c.format, c.title, c.number, c.number_sort, c.volume, c.summary, c.released_at, c.age_rating, c.language, c.page_count, c.cover_page, c.state, c.state_detail, c.hydrated_at, c.indexed_at, c.metadata, c.locked_fields, c.created_at, c.updated_at, c.deleted_at, c.search_vector
FROM comics c
JOIN series s ON s.id = c.series_id
WHERE c.library_id = ANY($1::uuid[])
  AND c.deleted_at IS NULL
  AND c.state = 'ready'
  -- Album non commencé…
  AND NOT EXISTS (
      SELECT 1 FROM reading_progress p
      WHERE p.comic_id = c.id AND p.user_id = $2 AND p.status <> 'unread'
  )
  -- …dans une série dont au moins un album a été lu.
  AND EXISTS (
      SELECT 1 FROM reading_progress p
      JOIN comics c2 ON c2.id = p.comic_id
      WHERE c2.series_id = c.series_id AND p.user_id = $2 AND p.status = 'read'
  )
ORDER BY c.series_id, c.number_sort NULLS LAST, c.title
LIMIT $3
`

type ListNextInSeriesParams struct {
	LibraryIds []uuid.UUID
	UserID     uuid.UUID
	PageSize   int32
}

// Étagère « Suite de la série » : le premier album non lu de chaque série déjà
// entamée. C'est la suggestion la plus utile d'une page d'accueil de lecteur.
func (q *Queries) ListNextInSeries(ctx context.Context, arg ListNextInSeriesParams) ([]Comic, error) {
	rows, err := q.db.Query(ctx, listNextInSeries, arg.LibraryIds, arg.UserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comic{}
	for rows.Next() {
		var i Comic
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.SeriesID,
			&i.ObjectKey,
			&i.FileSize,
			&i.FileEtag,
			&i.ContentHash,
			&i.Format,
			&i.Title,
			&i.Number,
			&i.NumberSort,
			&i.Volume,
			&i.Summary,
			&i.ReleasedAt,
			&i.AgeRating,
			&i.Language,
			&i.PageCount,
			&i.CoverPage,
			&i.State,
			&i.StateDetail,
			&i.HydratedAt,
			&i.IndexedAt,
			&i.Metadata,
			&i.LockedFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentComics = `-- name: ListRecentComics :many
SELECT id, library_id, series_id, object_key, file_size, file_etag, content_hash, format, title, number, number_sort, volume, summary, released_at, age_rating, language, page_count, cover_page, state, state_detail, hydrated_at, indexed_at, metadata, locked_fields, created_at, updated_at, deleted_at, search_vector FROM comics
WHERE library_id = ANY($1::uuid[])
  AND deleted_at IS NULL
  AND state = 'ready'
  AND ($2::smallint IS NULL
       OR age_rating IS NULL
       OR age_rating <= $2::smallint)
ORDER BY created_at DESC
LIMIT $3
`

type ListRecentComicsParams struct {
	LibraryIds   []uuid.UUID
	MaxAgeRating *int16
	PageSize     int32
}

// Étagère d'accueil : les derniers albums ajoutés.
func (q *Queries) ListRecentComics(ctx context.Context, arg ListRecentComicsParams) ([]Comic, error) {
	rows, err := q.db.Query(ctx, listRecentComics, arg.LibraryIds, arg.MaxAgeRating, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comic{}
	for rows.Next() {
		var i Comic
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.SeriesID,
			&i.ObjectKey,
			&i.FileSize,
			&i.FileEtag,
			&i.ContentHash,
			&i.Format,
			&i.Title,
			&i.Number,
			&i.NumberSort,
			&i.Volume,
			&i.Summary,
			&i.ReleasedAt,
			&i.AgeRating,
			&i.Language,
			&i.PageCount,
			&i.CoverPage,
			&i.State,
			&i.StateDetail,
			&i.HydratedAt,
			&i.IndexedAt,
			&i.Metadata,
			&i.LockedFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesPage = `-- name: ListSeriesPage :many
SELECT id, library_id, name, sort_name, description, publisher, status, age_rating, year_started, cover_comic_id, comic_count, metadata, locked_fields, created_at, updated_at FROM series
WHERE library_id = ANY($1::uuid[])
  AND ($2::text = '' OR sort_name > $2)
ORDER BY sort_name
LIMIT $3
`

type ListSeriesPageParams struct {
	LibraryIds     []uuid.UUID
	CursorSortName string
	PageSize       int32
}

func (q *Queries) ListSeriesPage(ctx context.Context, arg ListSeriesPageParams) ([]Series, error) {
	rows, err := q.db.Query(ctx, listSeriesPage, arg.LibraryIds, arg.CursorSortName, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.SortName,
			&i.Description,
			&i.Publisher,
			&i.Status,
			&i.AgeRating,
			&i.YearStarted,
			&i.CoverComicID,
			&i.ComicCount,
			&i.Metadata,
			&i.LockedFields,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchComics = `-- name: SearchComics :many
SELECT id, library_id, series_id, object_key, file_size, file_etag, content_hash, format, title, number, number_sort, volume, summary, released_at, age_rating, language, page_count, cover_page, state, state_detail, hydrated_at, indexed_at, metadata, locked_fields, created_at, updated_at, deleted_at, search_vector, (
    ts_rank(search_vector, websearch_to_tsquery('simple', immutable_unaccent($1)))
    + word_similarity(immutable_unaccent($1), immutable_unaccent(title))
)::real AS rank
FROM comics
WHERE library_id = ANY($2::uuid[])
  AND deleted_at IS NULL
  AND ($3::smallint IS NULL
       OR age_rating IS NULL
       OR age_rating <= $3::smallint)
  AND (search_vector @@ websearch_to_tsquery('simple', immutable_unaccent($1))
       OR immutable_unaccent($1) <% immutable_unaccent(title))
ORDER BY rank DESC, title
LIMIT $4
`

type SearchComicsParams struct {
	Query        string
	LibraryIds   []uuid.UUID
	MaxAgeRating *int16
	PageSize     int32
}

type SearchComicsRow struct {
	ID           uuid.UUID
	LibraryID    uuid.UUID
	SeriesID     uuid.NullUUID
	ObjectKey    string
	FileSize     int64
	FileEtag     *string
	ContentHash  []byte
	Format       ComicFormat
	Title        string
	Number       *string
	NumberSort   pgtype.Numeric
	Volume       *int16
	Summary      *string
	ReleasedAt   pgtype.Date
	AgeRating    *int16
	Language     *string
	PageCount    int32
	CoverPage    int32
	State        ComicState
	StateDetail  *string
	HydratedAt   pgtype.Timestamptz
	IndexedAt    pgtype.Timestamptz
	Metadata     []byte
	LockedFields []string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	SearchVector interface{}
	Rank         float32
}

// Recherche plein texte, avec repli sur la similarité trigramme.
//
// Les deux sont combinés parce qu'ils échouent différemment :
// websearch_to_tsquery gère les expressions et les mots multiples mais rate
// les fautes de frappe ; la similarité trigramme rattrape « asterics » →
// « Astérix » mais ne comprend pas les requêtes à plusieurs mots.
//
// word_similarity plutôt que similarity : cette dernière compare la requête au
// titre ENTIER, si bien qu'un titre long fait chuter le score sous le seuil.
// Mesuré sur « asterics » contre « Astérix le Gaulois » : similarity = 0,27
// (rejeté), word_similarity = 0,67 (accepté). word_similarity cherche la
// meilleure sous-séquence de mots, ce qui est le comportement attendu quand on
// tape un seul mot d'un titre.
//
// Tout est désaccentué de part et d'autre : personne ne saisit les accents
// dans un champ de recherche, et c'est rédhibitoire sur de la BD franco-belge.
func (q *Queries) SearchComics(ctx context.Context, arg SearchComicsParams) ([]SearchComicsRow, error) {
	rows, err := q.db.Query(ctx, searchComics,
		arg.Query,
		arg.LibraryIds,
		arg.MaxAgeRating,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchComicsRow{}
	for rows.Next() {
		var i SearchComicsRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.SeriesID,
			&i.ObjectKey,
			&i.FileSize,
			&i.FileEtag,
			&i.ContentHash,
			&i.Format,
			&i.Title,
			&i.Number,
			&i.NumberSort,
			&i.Volume,
			&i.Summary,
			&i.ReleasedAt,
			&i.AgeRating,
			&i.Language,
			&i.PageCount,
			&i.CoverPage,
			&i.State,
			&i.StateDetail,
			&i.HydratedAt,
			&i.IndexedAt,
			&i.Metadata,
			&i.LockedFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SearchVector,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSeries = `-- name: SearchSeries :many
SELECT id, library_id, name, sort_name, description, publisher, status, age_rating, year_started, cover_comic_id, comic_count, metadata, locked_fields, created_at, updated_at, word_similarity(immutable_unaccent($1), immutable_unaccent(name))::real AS rank
FROM series
WHERE library_id = ANY($2::uuid[])
  AND (immutable_unaccent($1) <% immutable_unaccent(name) OR sort_name LIKE $3::text)
ORDER BY rank DESC, sort_name
LIMIT $4
`

type SearchSeriesParams struct {
	Query      string
	LibraryIds []uuid.UUID
	Prefix     string
	PageSize   int32
}

type SearchSeriesRow struct {
	ID           uuid.UUID
	LibraryID    uuid.UUID
	Name         string
	SortName     string
	Description  *string
	Publisher    *string
	Status       *string
	AgeRating    *int16
	YearStarted  *int16
	CoverComicID uuid.NullUUID
	ComicCount   int32
	Metadata     []byte
	LockedFields []string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Rank         float32
}

func (q *Queries) SearchSeries(ctx context.Context, arg SearchSeriesParams) ([]SearchSeriesRow, error) {
	rows, err := q.db.Query(ctx, searchSeries,
		arg.Query,
		arg.LibraryIds,
		arg.Prefix,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSeriesRow{}
	for rows.Next() {
		var i SearchSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.SortName,
			&i.Description,
			&i.Publisher,
			&i.Status,
			&i.AgeRating,
			&i.YearStarted,
			&i.CoverComicID,
			&i.ComicCount,
			&i.Metadata,
			&i.LockedFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
