// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getComicDetail = `-- name: GetComicDetail :one
SELECT comics.id, comics.library_id, comics.series_id, comics.object_key, comics.file_size, comics.file_etag, comics.content_hash, comics.format, comics.title, comics.number, comics.number_sort, comics.volume, comics.summary, comics.released_at, comics.age_rating, comics.language, comics.page_count, comics.cover_page, comics.state, comics.state_detail, comics.hydrated_at, comics.indexed_at, comics.metadata, comics.locked_fields, comics.created_at, comics.updated_at, comics.deleted_at, comics.search_vector, comics.cover_placeholder, comics.folder_path, comics.excluded_at, COALESCE(series.name, '')::text AS series_name
FROM comics
LEFT JOIN series ON series.id = comics.series_id
WHERE comics.id = $1 AND comics.deleted_at IS NULL AND comics.excluded_at IS NULL
`

type GetComicDetailRow struct {
	Comic      Comic
	SeriesName string
}

// Détail d'un album, avec le nom de sa série quand il en a une.
//
// La série est en LEFT JOIN : beaucoup d'albums sont des one-shots. On ne peut
// donc pas l'embarquer entière — sqlc en ferait une structure aux champs non
// nullables, et le scan échouerait sur le premier album sans série. Seul le nom
// est retenu, ramené à la chaîne vide, qui est déjà la façon dont le reste du
// code représente l'absence de série.
func (q *Queries) GetComicDetail(ctx context.Context, id uuid.UUID) (GetComicDetailRow, error) {
	row := q.db.QueryRow(ctx, getComicDetail, id)
	var i GetComicDetailRow
	err := row.Scan(
		&i.Comic.ID,
		&i.Comic.LibraryID,
		&i.Comic.SeriesID,
		&i.Comic.ObjectKey,
		&i.Comic.FileSize,
		&i.Comic.FileEtag,
		&i.Comic.ContentHash,
		&i.Comic.Format,
		&i.Comic.Title,
		&i.Comic.Number,
		&i.Comic.NumberSort,
		&i.Comic.Volume,
		&i.Comic.Summary,
		&i.Comic.ReleasedAt,
		&i.Comic.AgeRating,
		&i.Comic.Language,
		&i.Comic.PageCount,
		&i.Comic.CoverPage,
		&i.Comic.State,
		&i.Comic.StateDetail,
		&i.Comic.HydratedAt,
		&i.Comic.IndexedAt,
		&i.Comic.Metadata,
		&i.Comic.LockedFields,
		&i.Comic.CreatedAt,
		&i.Comic.UpdatedAt,
		&i.Comic.DeletedAt,
		&i.Comic.SearchVector,
		&i.Comic.CoverPlaceholder,
		&i.Comic.FolderPath,
		&i.Comic.ExcludedAt,
		&i.SeriesName,
	)
	return i, err
}

const listComicsBySeries = `-- name: ListComicsBySeries :many
SELECT c.id, c.library_id, c.series_id, c.object_key, c.file_size, c.file_etag, c.content_hash, c.format, c.title, c.number, c.number_sort, c.volume, c.summary, c.released_at, c.age_rating, c.language, c.page_count, c.cover_page, c.state, c.state_detail, c.hydrated_at, c.indexed_at, c.metadata, c.locked_fields, c.created_at, c.updated_at, c.deleted_at, c.search_vector, c.cover_placeholder, c.folder_path, c.excluded_at, COALESCE(s.name, '')::text AS series_name
FROM comics c
LEFT JOIN series s ON s.id = c.series_id
WHERE c.series_id = $1 AND c.deleted_at IS NULL
  AND c.excluded_at IS NULL
  -- Dossiers masqués par un code non saisi. La comparaison couvre les
  -- sous-dossiers : masquer « Privé » masque tout ce qu'il contient.
  AND NOT EXISTS (
      SELECT 1 FROM unnest($2::text[]) AS locked(p)
      WHERE c.folder_path = locked.p OR c.folder_path LIKE locked.p || '/%'
  )
ORDER BY c.number_sort NULLS LAST, c.title
`

type ListComicsBySeriesParams struct {
	SeriesID    uuid.NullUUID
	LockedPaths []string
}

type ListComicsBySeriesRow struct {
	Comic      Comic
	SeriesName string
}

func (q *Queries) ListComicsBySeries(ctx context.Context, arg ListComicsBySeriesParams) ([]ListComicsBySeriesRow, error) {
	rows, err := q.db.Query(ctx, listComicsBySeries, arg.SeriesID, arg.LockedPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComicsBySeriesRow{}
	for rows.Next() {
		var i ListComicsBySeriesRow
		if err := rows.Scan(
			&i.Comic.ID,
			&i.Comic.LibraryID,
			&i.Comic.SeriesID,
			&i.Comic.ObjectKey,
			&i.Comic.FileSize,
			&i.Comic.FileEtag,
			&i.Comic.ContentHash,
			&i.Comic.Format,
			&i.Comic.Title,
			&i.Comic.Number,
			&i.Comic.NumberSort,
			&i.Comic.Volume,
			&i.Comic.Summary,
			&i.Comic.ReleasedAt,
			&i.Comic.AgeRating,
			&i.Comic.Language,
			&i.Comic.PageCount,
			&i.Comic.CoverPage,
			&i.Comic.State,
			&i.Comic.StateDetail,
			&i.Comic.HydratedAt,
			&i.Comic.IndexedAt,
			&i.Comic.Metadata,
			&i.Comic.LockedFields,
			&i.Comic.CreatedAt,
			&i.Comic.UpdatedAt,
			&i.Comic.DeletedAt,
			&i.Comic.SearchVector,
			&i.Comic.CoverPlaceholder,
			&i.Comic.FolderPath,
			&i.Comic.ExcludedAt,
			&i.SeriesName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComicsPage = `-- name: ListComicsPage :many

SELECT c.id, c.library_id, c.series_id, c.object_key, c.file_size, c.file_etag, c.content_hash, c.format, c.title, c.number, c.number_sort, c.volume, c.summary, c.released_at, c.age_rating, c.language, c.page_count, c.cover_page, c.state, c.state_detail, c.hydrated_at, c.indexed_at, c.metadata, c.locked_fields, c.created_at, c.updated_at, c.deleted_at, c.search_vector, c.cover_placeholder, c.folder_path, c.excluded_at, COALESCE(s.name, '')::text AS series_name
FROM comics c
LEFT JOIN series s ON s.id = c.series_id
LEFT JOIN reading_progress p
       ON p.comic_id = c.id AND p.user_id = $1
WHERE c.library_id = ANY($2::uuid[])
  AND c.deleted_at IS NULL
  AND c.excluded_at IS NULL
  -- Dossiers masqués par un code non saisi. La comparaison couvre les
  -- sous-dossiers : masquer « Privé » masque tout ce qu'il contient.
  AND NOT EXISTS (
      SELECT 1 FROM unnest($3::text[]) AS locked(p)
      WHERE c.folder_path = locked.p OR c.folder_path LIKE locked.p || '/%'
  )
  AND ($4::uuid IS NULL OR c.series_id = $4::uuid)
  AND ($5::text = '' OR c.state::text = $5)
  -- Filtrage par dossier. Le préfixe permet d'inclure les sous-dossiers, ce
  -- qu'attend un utilisateur qui clique sur un nœud de l'arbre.
  AND ($6::text IS NULL
       OR c.folder_path = $6::text
       OR c.folder_path LIKE $6::text || '/%')
  AND ($7::boolean = false
       OR EXISTS (SELECT 1 FROM favorites f
                  WHERE f.comic_id = c.id AND f.user_id = $1))
  -- Filtrage par classification d'âge, pour les profils restreints.
  AND ($8::smallint IS NULL
       OR c.age_rating IS NULL
       OR c.age_rating <= $8::smallint)
  -- Filtrage par statut de lecture. « unread » couvre l'absence de ligne :
  -- un album jamais ouvert n'a pas d'entrée dans reading_progress.
  AND ($9::text = ''
       OR ($9 = 'unread'      AND (p.status IS NULL OR p.status = 'unread'))
       OR ($9 = 'in_progress' AND p.status = 'in_progress')
       OR ($9 = 'read'        AND p.status = 'read'))
  -- Curseur, dans l'ordre du tri demandé.
  AND (
    CASE $10::text
      WHEN 'title' THEN
        $11::text IS NULL
        OR (c.title, c.id) > ($11::text, $12::uuid)
      WHEN 'released' THEN
        $13::date IS NULL
        OR (c.released_at, c.id) < ($13::date, $12::uuid)
      ELSE
        $14::timestamptz IS NULL
        OR (c.created_at, c.id) < ($14::timestamptz, $12::uuid)
    END
  )
ORDER BY
  CASE WHEN $10 = 'title'    THEN c.title END ASC,
  CASE WHEN $10 = 'released' THEN c.released_at END DESC NULLS LAST,
  CASE WHEN $10 NOT IN ('title', 'released') THEN c.created_at END DESC,
  c.id DESC
LIMIT $15
`

type ListComicsPageParams struct {
	UserID          uuid.UUID
	LibraryIds      []uuid.UUID
	LockedPaths     []string
	SeriesID        uuid.NullUUID
	State           string
	Folder          *string
	FavoritesOnly   bool
	MaxAgeRating    *int16
	ReadStatus      string
	Sort            string
	CursorTitle     *string
	CursorID        uuid.NullUUID
	CursorReleased  pgtype.Date
	CursorCreatedAt pgtype.Timestamptz
	PageSize        int32
}

type ListComicsPageRow struct {
	Comic      Comic
	SeriesName string
}

// Requêtes de consultation du catalogue.
//
// Pagination par curseur plutôt que par OFFSET : sur une bibliothèque de
// plusieurs milliers de titres, OFFSET force PostgreSQL à parcourir puis jeter
// toutes les lignes précédentes, et une insertion pendant la pagination décale
// silencieusement les résultats. Le curseur est stable et à coût constant.
// Liste paginée, filtrable et triable.
//
// Le tri est porté par la requête plutôt que par une concaténation côté Go :
// une clause ORDER BY construite en chaîne serait une porte d'injection, et le
// plan d'exécution ne serait plus mis en cache. Les trois ordres possibles sont
// donc écrits en dur, sélectionnés par un paramètre.
//
// Le curseur suit l'ordre choisi : (created_at, id) pour le tri par ajout,
// (title, id) pour le tri alphabétique. Un seul curseur composite ne
// conviendrait pas aux deux.
func (q *Queries) ListComicsPage(ctx context.Context, arg ListComicsPageParams) ([]ListComicsPageRow, error) {
	rows, err := q.db.Query(ctx, listComicsPage,
		arg.UserID,
		arg.LibraryIds,
		arg.LockedPaths,
		arg.SeriesID,
		arg.State,
		arg.Folder,
		arg.FavoritesOnly,
		arg.MaxAgeRating,
		arg.ReadStatus,
		arg.Sort,
		arg.CursorTitle,
		arg.CursorID,
		arg.CursorReleased,
		arg.CursorCreatedAt,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComicsPageRow{}
	for rows.Next() {
		var i ListComicsPageRow
		if err := rows.Scan(
			&i.Comic.ID,
			&i.Comic.LibraryID,
			&i.Comic.SeriesID,
			&i.Comic.ObjectKey,
			&i.Comic.FileSize,
			&i.Comic.FileEtag,
			&i.Comic.ContentHash,
			&i.Comic.Format,
			&i.Comic.Title,
			&i.Comic.Number,
			&i.Comic.NumberSort,
			&i.Comic.Volume,
			&i.Comic.Summary,
			&i.Comic.ReleasedAt,
			&i.Comic.AgeRating,
			&i.Comic.Language,
			&i.Comic.PageCount,
			&i.Comic.CoverPage,
			&i.Comic.State,
			&i.Comic.StateDetail,
			&i.Comic.HydratedAt,
			&i.Comic.IndexedAt,
			&i.Comic.Metadata,
			&i.Comic.LockedFields,
			&i.Comic.CreatedAt,
			&i.Comic.UpdatedAt,
			&i.Comic.DeletedAt,
			&i.Comic.SearchVector,
			&i.Comic.CoverPlaceholder,
			&i.Comic.FolderPath,
			&i.Comic.ExcludedAt,
			&i.SeriesName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNextInSeries = `-- name: ListNextInSeries :many
SELECT DISTINCT ON (c.series_id) c.id, c.library_id, c.series_id, c.object_key, c.file_size, c.file_etag, c.content_hash, c.format, c.title, c.number, c.number_sort, c.volume, c.summary, c.released_at, c.age_rating, c.language, c.page_count, c.cover_page, c.state, c.state_detail, c.hydrated_at, c.indexed_at, c.metadata, c.locked_fields, c.created_at, c.updated_at, c.deleted_at, c.search_vector, c.cover_placeholder, c.folder_path, c.excluded_at, s.name AS series_name
FROM comics c
JOIN series s ON s.id = c.series_id
WHERE c.library_id = ANY($1::uuid[])
  AND c.deleted_at IS NULL
  AND c.excluded_at IS NULL
  AND c.state = 'ready'
  -- Dossiers masqués par un code non saisi. La comparaison couvre les
  -- sous-dossiers : masquer « Privé » masque tout ce qu'il contient.
  AND NOT EXISTS (
      SELECT 1 FROM unnest($2::text[]) AS locked(p)
      WHERE c.folder_path = locked.p OR c.folder_path LIKE locked.p || '/%'
  )
  -- Album non commencé…
  AND NOT EXISTS (
      SELECT 1 FROM reading_progress p
      WHERE p.comic_id = c.id AND p.user_id = $3 AND p.status <> 'unread'
  )
  -- …dans une série dont au moins un album a été lu.
  AND EXISTS (
      SELECT 1 FROM reading_progress p
      JOIN comics c2 ON c2.id = p.comic_id
      WHERE c2.series_id = c.series_id AND p.user_id = $3 AND p.status = 'read'
  )
ORDER BY c.series_id, c.number_sort NULLS LAST, c.title
LIMIT $4
`

type ListNextInSeriesParams struct {
	LibraryIds  []uuid.UUID
	LockedPaths []string
	UserID      uuid.UUID
	PageSize    int32
}

type ListNextInSeriesRow struct {
	Comic      Comic
	SeriesName string
}

// Étagère « Suite de la série » : le premier album non lu de chaque série déjà
// entamée. C'est la suggestion la plus utile d'une page d'accueil de lecteur.
func (q *Queries) ListNextInSeries(ctx context.Context, arg ListNextInSeriesParams) ([]ListNextInSeriesRow, error) {
	rows, err := q.db.Query(ctx, listNextInSeries,
		arg.LibraryIds,
		arg.LockedPaths,
		arg.UserID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNextInSeriesRow{}
	for rows.Next() {
		var i ListNextInSeriesRow
		if err := rows.Scan(
			&i.Comic.ID,
			&i.Comic.LibraryID,
			&i.Comic.SeriesID,
			&i.Comic.ObjectKey,
			&i.Comic.FileSize,
			&i.Comic.FileEtag,
			&i.Comic.ContentHash,
			&i.Comic.Format,
			&i.Comic.Title,
			&i.Comic.Number,
			&i.Comic.NumberSort,
			&i.Comic.Volume,
			&i.Comic.Summary,
			&i.Comic.ReleasedAt,
			&i.Comic.AgeRating,
			&i.Comic.Language,
			&i.Comic.PageCount,
			&i.Comic.CoverPage,
			&i.Comic.State,
			&i.Comic.StateDetail,
			&i.Comic.HydratedAt,
			&i.Comic.IndexedAt,
			&i.Comic.Metadata,
			&i.Comic.LockedFields,
			&i.Comic.CreatedAt,
			&i.Comic.UpdatedAt,
			&i.Comic.DeletedAt,
			&i.Comic.SearchVector,
			&i.Comic.CoverPlaceholder,
			&i.Comic.FolderPath,
			&i.Comic.ExcludedAt,
			&i.SeriesName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentComics = `-- name: ListRecentComics :many
SELECT c.id, c.library_id, c.series_id, c.object_key, c.file_size, c.file_etag, c.content_hash, c.format, c.title, c.number, c.number_sort, c.volume, c.summary, c.released_at, c.age_rating, c.language, c.page_count, c.cover_page, c.state, c.state_detail, c.hydrated_at, c.indexed_at, c.metadata, c.locked_fields, c.created_at, c.updated_at, c.deleted_at, c.search_vector, c.cover_placeholder, c.folder_path, c.excluded_at, COALESCE(s.name, '')::text AS series_name
FROM comics c
LEFT JOIN series s ON s.id = c.series_id
WHERE c.library_id = ANY($1::uuid[])
  AND c.deleted_at IS NULL
  AND c.excluded_at IS NULL
  AND c.state = 'ready'
  -- Dossiers masqués par un code non saisi. La comparaison couvre les
  -- sous-dossiers : masquer « Privé » masque tout ce qu'il contient.
  AND NOT EXISTS (
      SELECT 1 FROM unnest($2::text[]) AS locked(p)
      WHERE c.folder_path = locked.p OR c.folder_path LIKE locked.p || '/%'
  )
  AND ($3::smallint IS NULL
       OR c.age_rating IS NULL
       OR c.age_rating <= $3::smallint)
ORDER BY c.created_at DESC
LIMIT $4
`

type ListRecentComicsParams struct {
	LibraryIds   []uuid.UUID
	LockedPaths  []string
	MaxAgeRating *int16
	PageSize     int32
}

type ListRecentComicsRow struct {
	Comic      Comic
	SeriesName string
}

// Étagère d'accueil : les derniers albums ajoutés.
func (q *Queries) ListRecentComics(ctx context.Context, arg ListRecentComicsParams) ([]ListRecentComicsRow, error) {
	rows, err := q.db.Query(ctx, listRecentComics,
		arg.LibraryIds,
		arg.LockedPaths,
		arg.MaxAgeRating,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentComicsRow{}
	for rows.Next() {
		var i ListRecentComicsRow
		if err := rows.Scan(
			&i.Comic.ID,
			&i.Comic.LibraryID,
			&i.Comic.SeriesID,
			&i.Comic.ObjectKey,
			&i.Comic.FileSize,
			&i.Comic.FileEtag,
			&i.Comic.ContentHash,
			&i.Comic.Format,
			&i.Comic.Title,
			&i.Comic.Number,
			&i.Comic.NumberSort,
			&i.Comic.Volume,
			&i.Comic.Summary,
			&i.Comic.ReleasedAt,
			&i.Comic.AgeRating,
			&i.Comic.Language,
			&i.Comic.PageCount,
			&i.Comic.CoverPage,
			&i.Comic.State,
			&i.Comic.StateDetail,
			&i.Comic.HydratedAt,
			&i.Comic.IndexedAt,
			&i.Comic.Metadata,
			&i.Comic.LockedFields,
			&i.Comic.CreatedAt,
			&i.Comic.UpdatedAt,
			&i.Comic.DeletedAt,
			&i.Comic.SearchVector,
			&i.Comic.CoverPlaceholder,
			&i.Comic.FolderPath,
			&i.Comic.ExcludedAt,
			&i.SeriesName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesPage = `-- name: ListSeriesPage :many
SELECT id, library_id, name, sort_name, description, publisher, status, age_rating, year_started, cover_comic_id, comic_count, metadata, locked_fields, created_at, updated_at FROM series
WHERE library_id = ANY($1::uuid[])
  AND ($2::text = '' OR sort_name > $2)
ORDER BY sort_name
LIMIT $3
`

type ListSeriesPageParams struct {
	LibraryIds     []uuid.UUID
	CursorSortName string
	PageSize       int32
}

func (q *Queries) ListSeriesPage(ctx context.Context, arg ListSeriesPageParams) ([]Series, error) {
	rows, err := q.db.Query(ctx, listSeriesPage, arg.LibraryIds, arg.CursorSortName, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.SortName,
			&i.Description,
			&i.Publisher,
			&i.Status,
			&i.AgeRating,
			&i.YearStarted,
			&i.CoverComicID,
			&i.ComicCount,
			&i.Metadata,
			&i.LockedFields,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchComics = `-- name: SearchComics :many
SELECT c.id, c.library_id, c.series_id, c.object_key, c.file_size, c.file_etag, c.content_hash, c.format, c.title, c.number, c.number_sort, c.volume, c.summary, c.released_at, c.age_rating, c.language, c.page_count, c.cover_page, c.state, c.state_detail, c.hydrated_at, c.indexed_at, c.metadata, c.locked_fields, c.created_at, c.updated_at, c.deleted_at, c.search_vector, c.cover_placeholder, c.folder_path, c.excluded_at, COALESCE(s.name, '')::text AS series_name, (
    ts_rank(c.search_vector, websearch_to_tsquery('simple', immutable_unaccent($1)))
    + word_similarity(immutable_unaccent($1), immutable_unaccent(c.title))
)::real AS rank
FROM comics c
LEFT JOIN series s ON s.id = c.series_id
WHERE c.library_id = ANY($2::uuid[])
  AND c.deleted_at IS NULL
  AND c.excluded_at IS NULL
  -- Dossiers masqués par un code non saisi. La comparaison couvre les
  -- sous-dossiers : masquer « Privé » masque tout ce qu'il contient.
  AND NOT EXISTS (
      SELECT 1 FROM unnest($3::text[]) AS locked(p)
      WHERE c.folder_path = locked.p OR c.folder_path LIKE locked.p || '/%'
  )
  AND ($4::smallint IS NULL
       OR c.age_rating IS NULL
       OR c.age_rating <= $4::smallint)
  AND (c.search_vector @@ websearch_to_tsquery('simple', immutable_unaccent($1))
       OR immutable_unaccent($1) <% immutable_unaccent(c.title))
ORDER BY rank DESC, c.title
LIMIT $5
`

type SearchComicsParams struct {
	Query        string
	LibraryIds   []uuid.UUID
	LockedPaths  []string
	MaxAgeRating *int16
	PageSize     int32
}

type SearchComicsRow struct {
	Comic      Comic
	SeriesName string
	Rank       float32
}

// Recherche plein texte, avec repli sur la similarité trigramme.
//
// Les deux sont combinés parce qu'ils échouent différemment :
// websearch_to_tsquery gère les expressions et les mots multiples mais rate
// les fautes de frappe ; la similarité trigramme rattrape « asterics » →
// « Astérix » mais ne comprend pas les requêtes à plusieurs mots.
//
// word_similarity plutôt que similarity : cette dernière compare la requête au
// titre ENTIER, si bien qu'un titre long fait chuter le score sous le seuil.
// Mesuré sur « asterics » contre « Astérix le Gaulois » : similarity = 0,27
// (rejeté), word_similarity = 0,67 (accepté). word_similarity cherche la
// meilleure sous-séquence de mots, ce qui est le comportement attendu quand on
// tape un seul mot d'un titre.
//
// Tout est désaccentué de part et d'autre : personne ne saisit les accents
// dans un champ de recherche, et c'est rédhibitoire sur de la BD franco-belge.
func (q *Queries) SearchComics(ctx context.Context, arg SearchComicsParams) ([]SearchComicsRow, error) {
	rows, err := q.db.Query(ctx, searchComics,
		arg.Query,
		arg.LibraryIds,
		arg.LockedPaths,
		arg.MaxAgeRating,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchComicsRow{}
	for rows.Next() {
		var i SearchComicsRow
		if err := rows.Scan(
			&i.Comic.ID,
			&i.Comic.LibraryID,
			&i.Comic.SeriesID,
			&i.Comic.ObjectKey,
			&i.Comic.FileSize,
			&i.Comic.FileEtag,
			&i.Comic.ContentHash,
			&i.Comic.Format,
			&i.Comic.Title,
			&i.Comic.Number,
			&i.Comic.NumberSort,
			&i.Comic.Volume,
			&i.Comic.Summary,
			&i.Comic.ReleasedAt,
			&i.Comic.AgeRating,
			&i.Comic.Language,
			&i.Comic.PageCount,
			&i.Comic.CoverPage,
			&i.Comic.State,
			&i.Comic.StateDetail,
			&i.Comic.HydratedAt,
			&i.Comic.IndexedAt,
			&i.Comic.Metadata,
			&i.Comic.LockedFields,
			&i.Comic.CreatedAt,
			&i.Comic.UpdatedAt,
			&i.Comic.DeletedAt,
			&i.Comic.SearchVector,
			&i.Comic.CoverPlaceholder,
			&i.Comic.FolderPath,
			&i.Comic.ExcludedAt,
			&i.SeriesName,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSeries = `-- name: SearchSeries :many
SELECT id, library_id, name, sort_name, description, publisher, status, age_rating, year_started, cover_comic_id, comic_count, metadata, locked_fields, created_at, updated_at, word_similarity(immutable_unaccent($1), immutable_unaccent(name))::real AS rank
FROM series
WHERE library_id = ANY($2::uuid[])
  AND (immutable_unaccent($1) <% immutable_unaccent(name) OR sort_name LIKE $3::text)
ORDER BY rank DESC, sort_name
LIMIT $4
`

type SearchSeriesParams struct {
	Query      string
	LibraryIds []uuid.UUID
	Prefix     string
	PageSize   int32
}

type SearchSeriesRow struct {
	ID           uuid.UUID
	LibraryID    uuid.UUID
	Name         string
	SortName     string
	Description  *string
	Publisher    *string
	Status       *string
	AgeRating    *int16
	YearStarted  *int16
	CoverComicID uuid.NullUUID
	ComicCount   int32
	Metadata     []byte
	LockedFields []string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Rank         float32
}

func (q *Queries) SearchSeries(ctx context.Context, arg SearchSeriesParams) ([]SearchSeriesRow, error) {
	rows, err := q.db.Query(ctx, searchSeries,
		arg.Query,
		arg.LibraryIds,
		arg.Prefix,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSeriesRow{}
	for rows.Next() {
		var i SearchSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.SortName,
			&i.Description,
			&i.Publisher,
			&i.Status,
			&i.AgeRating,
			&i.YearStarted,
			&i.CoverComicID,
			&i.ComicCount,
			&i.Metadata,
			&i.LockedFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
