// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comics.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyComicMetadata = `-- name: ApplyComicMetadata :exec
UPDATE comics
SET title       = CASE WHEN 'title'       = ANY(locked_fields) THEN title       ELSE coalesce($3, title) END,
    number      = CASE WHEN 'number'      = ANY(locked_fields) THEN number      ELSE coalesce($4, number) END,
    number_sort = CASE WHEN 'number'      = ANY(locked_fields) THEN number_sort ELSE coalesce($5, number_sort) END,
    volume      = CASE WHEN 'volume'      = ANY(locked_fields) THEN volume      ELSE coalesce($6, volume) END,
    summary     = CASE WHEN 'summary'     = ANY(locked_fields) THEN summary     ELSE coalesce($7, summary) END,
    released_at = CASE WHEN 'released_at' = ANY(locked_fields) THEN released_at ELSE coalesce($8, released_at) END,
    age_rating  = CASE WHEN 'age_rating'  = ANY(locked_fields) THEN age_rating  ELSE coalesce($9, age_rating) END,
    language    = CASE WHEN 'language'    = ANY(locked_fields) THEN language    ELSE coalesce($10, language) END,
    series_id   = coalesce($11, series_id),
    metadata    = $2
WHERE id = $1
`

type ApplyComicMetadataParams struct {
	ID         uuid.UUID
	Metadata   []byte
	Title      *string
	Number     *string
	NumberSort pgtype.Numeric
	Volume     *int16
	Summary    *string
	ReleasedAt pgtype.Date
	AgeRating  *int16
	Language   *string
	SeriesID   uuid.NullUUID
}

// Applique les métadonnées issues de ComicInfo.xml ou du nom de fichier.
// Les champs présents dans locked_fields sont préservés : une saisie manuelle
// ne doit jamais être écrasée par un rescan.
func (q *Queries) ApplyComicMetadata(ctx context.Context, arg ApplyComicMetadataParams) error {
	_, err := q.db.Exec(ctx, applyComicMetadata,
		arg.ID,
		arg.Metadata,
		arg.Title,
		arg.Number,
		arg.NumberSort,
		arg.Volume,
		arg.Summary,
		arg.ReleasedAt,
		arg.AgeRating,
		arg.Language,
		arg.SeriesID,
	)
	return err
}

const cacheStats = `-- name: CacheStats :one
SELECT
    count(*)::bigint                          AS entries,
    coalesce(sum(size), 0)::bigint            AS bytes,
    coalesce(sum(hits), 0)::bigint            AS hits,
    min(created_at)::timestamptz              AS oldest_at,
    max(last_hit_at)::timestamptz             AS newest_hit_at
FROM cache_entries
`

type CacheStatsRow struct {
	Entries     int64
	Bytes       int64
	Hits        int64
	OldestAt    pgtype.Timestamptz
	NewestHitAt pgtype.Timestamptz
}

// Inventaire du cache dérivé, pour l'écran d'administration.
//
// Une seule requête plutôt que trois : l'écran les affiche ensemble, et trois
// allers-retours pour peupler le même encart seraient du gâchis.
func (q *Queries) CacheStats(ctx context.Context) (CacheStatsRow, error) {
	row := q.db.QueryRow(ctx, cacheStats)
	var i CacheStatsRow
	err := row.Scan(
		&i.Entries,
		&i.Bytes,
		&i.Hits,
		&i.OldestAt,
		&i.NewestHitAt,
	)
	return i, err
}

const countComicPages = `-- name: CountComicPages :one
SELECT count(*) FROM comic_pages WHERE comic_id = $1
`

func (q *Queries) CountComicPages(ctx context.Context, comicID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countComicPages, comicID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countComicsByLibrary = `-- name: CountComicsByLibrary :one
SELECT count(*) FROM comics WHERE library_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountComicsByLibrary(ctx context.Context, libraryID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countComicsByLibrary, libraryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCacheEntry = `-- name: DeleteCacheEntry :exec
DELETE FROM cache_entries WHERE key = $1
`

func (q *Queries) DeleteCacheEntry(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteCacheEntry, key)
	return err
}

const deleteComic = `-- name: DeleteComic :exec
DELETE FROM comics WHERE id = $1
`

func (q *Queries) DeleteComic(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteComic, id)
	return err
}

const deleteComicPages = `-- name: DeleteComicPages :exec

DELETE FROM comic_pages WHERE comic_id = $1
`

// ─── Pages ───────────────────────────────────────────────────────────────────
func (q *Queries) DeleteComicPages(ctx context.Context, comicID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteComicPages, comicID)
	return err
}

const getComic = `-- name: GetComic :one
SELECT id, library_id, series_id, object_key, file_size, file_etag, content_hash, format, title, number, number_sort, volume, summary, released_at, age_rating, language, page_count, cover_page, state, state_detail, hydrated_at, indexed_at, metadata, locked_fields, created_at, updated_at, deleted_at, search_vector, cover_placeholder, folder_path, excluded_at, hydrated_key FROM comics WHERE id = $1
`

func (q *Queries) GetComic(ctx context.Context, id uuid.UUID) (Comic, error) {
	row := q.db.QueryRow(ctx, getComic, id)
	var i Comic
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.SeriesID,
		&i.ObjectKey,
		&i.FileSize,
		&i.FileEtag,
		&i.ContentHash,
		&i.Format,
		&i.Title,
		&i.Number,
		&i.NumberSort,
		&i.Volume,
		&i.Summary,
		&i.ReleasedAt,
		&i.AgeRating,
		&i.Language,
		&i.PageCount,
		&i.CoverPage,
		&i.State,
		&i.StateDetail,
		&i.HydratedAt,
		&i.IndexedAt,
		&i.Metadata,
		&i.LockedFields,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
		&i.CoverPlaceholder,
		&i.FolderPath,
		&i.ExcludedAt,
		&i.HydratedKey,
	)
	return i, err
}

const getComicByObjectKey = `-- name: GetComicByObjectKey :one
SELECT id, library_id, series_id, object_key, file_size, file_etag, content_hash, format, title, number, number_sort, volume, summary, released_at, age_rating, language, page_count, cover_page, state, state_detail, hydrated_at, indexed_at, metadata, locked_fields, created_at, updated_at, deleted_at, search_vector, cover_placeholder, folder_path, excluded_at, hydrated_key FROM comics WHERE library_id = $1 AND object_key = $2
`

type GetComicByObjectKeyParams struct {
	LibraryID uuid.UUID
	ObjectKey string
}

func (q *Queries) GetComicByObjectKey(ctx context.Context, arg GetComicByObjectKeyParams) (Comic, error) {
	row := q.db.QueryRow(ctx, getComicByObjectKey, arg.LibraryID, arg.ObjectKey)
	var i Comic
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.SeriesID,
		&i.ObjectKey,
		&i.FileSize,
		&i.FileEtag,
		&i.ContentHash,
		&i.Format,
		&i.Title,
		&i.Number,
		&i.NumberSort,
		&i.Volume,
		&i.Summary,
		&i.ReleasedAt,
		&i.AgeRating,
		&i.Language,
		&i.PageCount,
		&i.CoverPage,
		&i.State,
		&i.StateDetail,
		&i.HydratedAt,
		&i.IndexedAt,
		&i.Metadata,
		&i.LockedFields,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
		&i.CoverPlaceholder,
		&i.FolderPath,
		&i.ExcludedAt,
		&i.HydratedKey,
	)
	return i, err
}

const getComicPage = `-- name: GetComicPage :one
SELECT comic_id, index, entry_name, data_offset, data_size, size, compression, width, height, is_double FROM comic_pages
WHERE comic_id = $1 AND index = $2
`

type GetComicPageParams struct {
	ComicID uuid.UUID
	Index   int32
}

// ★ La requête du chemin chaud : servir une page.
// Un seul aller-retour en base, puis un seul ReadRange sur le backend.
func (q *Queries) GetComicPage(ctx context.Context, arg GetComicPageParams) (ComicPage, error) {
	row := q.db.QueryRow(ctx, getComicPage, arg.ComicID, arg.Index)
	var i ComicPage
	err := row.Scan(
		&i.ComicID,
		&i.Index,
		&i.EntryName,
		&i.DataOffset,
		&i.DataSize,
		&i.Size,
		&i.Compression,
		&i.Width,
		&i.Height,
		&i.IsDouble,
	)
	return i, err
}

const getSeries = `-- name: GetSeries :one
SELECT id, library_id, name, sort_name, description, publisher, status, age_rating, year_started, cover_comic_id, comic_count, metadata, locked_fields, created_at, updated_at FROM series WHERE id = $1
`

func (q *Queries) GetSeries(ctx context.Context, id uuid.UUID) (Series, error) {
	row := q.db.QueryRow(ctx, getSeries, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Name,
		&i.SortName,
		&i.Description,
		&i.Publisher,
		&i.Status,
		&i.AgeRating,
		&i.YearStarted,
		&i.CoverComicID,
		&i.ComicCount,
		&i.Metadata,
		&i.LockedFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertComicPage = `-- name: InsertComicPage :exec
INSERT INTO comic_pages (
    comic_id, index, entry_name, data_offset, data_size, size, compression, width, height, is_double
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertComicPageParams struct {
	ComicID     uuid.UUID
	Index       int32
	EntryName   string
	DataOffset  *int64
	DataSize    *int64
	Size        *int64
	Compression *int16
	Width       *int32
	Height      *int32
	IsDouble    bool
}

func (q *Queries) InsertComicPage(ctx context.Context, arg InsertComicPageParams) error {
	_, err := q.db.Exec(ctx, insertComicPage,
		arg.ComicID,
		arg.Index,
		arg.EntryName,
		arg.DataOffset,
		arg.DataSize,
		arg.Size,
		arg.Compression,
		arg.Width,
		arg.Height,
		arg.IsDouble,
	)
	return err
}

const listCacheEntriesForEviction = `-- name: ListCacheEntriesForEviction :many
SELECT key, size FROM cache_entries
ORDER BY last_hit_at
LIMIT $1
`

type ListCacheEntriesForEvictionRow struct {
	Key  string
	Size int64
}

func (q *Queries) ListCacheEntriesForEviction(ctx context.Context, limit int32) ([]ListCacheEntriesForEvictionRow, error) {
	rows, err := q.db.Query(ctx, listCacheEntriesForEviction, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCacheEntriesForEvictionRow{}
	for rows.Next() {
		var i ListCacheEntriesForEvictionRow
		if err := rows.Scan(&i.Key, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComicPages = `-- name: ListComicPages :many
SELECT comic_id, index, entry_name, data_offset, data_size, size, compression, width, height, is_double FROM comic_pages
WHERE comic_id = $1
ORDER BY index
`

func (q *Queries) ListComicPages(ctx context.Context, comicID uuid.UUID) ([]ComicPage, error) {
	rows, err := q.db.Query(ctx, listComicPages, comicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComicPage{}
	for rows.Next() {
		var i ComicPage
		if err := rows.Scan(
			&i.ComicID,
			&i.Index,
			&i.EntryName,
			&i.DataOffset,
			&i.DataSize,
			&i.Size,
			&i.Compression,
			&i.Width,
			&i.Height,
			&i.IsDouble,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComicsByLibrary = `-- name: ListComicsByLibrary :many
SELECT id, library_id, series_id, object_key, file_size, file_etag, content_hash, format, title, number, number_sort, volume, summary, released_at, age_rating, language, page_count, cover_page, state, state_detail, hydrated_at, indexed_at, metadata, locked_fields, created_at, updated_at, deleted_at, search_vector, cover_placeholder, folder_path, excluded_at, hydrated_key FROM comics
WHERE library_id = $1 AND deleted_at IS NULL
ORDER BY title
LIMIT $2 OFFSET $3
`

type ListComicsByLibraryParams struct {
	LibraryID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListComicsByLibrary(ctx context.Context, arg ListComicsByLibraryParams) ([]Comic, error) {
	rows, err := q.db.Query(ctx, listComicsByLibrary, arg.LibraryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comic{}
	for rows.Next() {
		var i Comic
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.SeriesID,
			&i.ObjectKey,
			&i.FileSize,
			&i.FileEtag,
			&i.ContentHash,
			&i.Format,
			&i.Title,
			&i.Number,
			&i.NumberSort,
			&i.Volume,
			&i.Summary,
			&i.ReleasedAt,
			&i.AgeRating,
			&i.Language,
			&i.PageCount,
			&i.CoverPage,
			&i.State,
			&i.StateDetail,
			&i.HydratedAt,
			&i.IndexedAt,
			&i.Metadata,
			&i.LockedFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SearchVector,
			&i.CoverPlaceholder,
			&i.FolderPath,
			&i.ExcludedAt,
			&i.HydratedKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesByLibrary = `-- name: ListSeriesByLibrary :many
SELECT id, library_id, name, sort_name, description, publisher, status, age_rating, year_started, cover_comic_id, comic_count, metadata, locked_fields, created_at, updated_at FROM series
WHERE library_id = $1
ORDER BY sort_name
`

func (q *Queries) ListSeriesByLibrary(ctx context.Context, libraryID uuid.UUID) ([]Series, error) {
	rows, err := q.db.Query(ctx, listSeriesByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.SortName,
			&i.Description,
			&i.Publisher,
			&i.Status,
			&i.AgeRating,
			&i.YearStarted,
			&i.CoverComicID,
			&i.ComicCount,
			&i.Metadata,
			&i.LockedFields,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMissingComicsDeleted = `-- name: MarkMissingComicsDeleted :execrows
UPDATE comics
SET deleted_at = now()
WHERE library_id = $1
  AND deleted_at IS NULL
  AND object_key <> ALL($2::text[])
`

type MarkMissingComicsDeletedParams struct {
	LibraryID uuid.UUID
	Column2   []string
}

// Marque comme supprimés les objets absents du dernier scan.
// On ne supprime pas la ligne : un backend momentanément injoignable ne doit
// pas détruire la progression de lecture des utilisateurs.
func (q *Queries) MarkMissingComicsDeleted(ctx context.Context, arg MarkMissingComicsDeletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMissingComicsDeleted, arg.LibraryID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeCacheEntries = `-- name: PurgeCacheEntries :many
DELETE FROM cache_entries RETURNING key, size
`

type PurgeCacheEntriesRow struct {
	Key  string
	Size int64
}

// Vide l'inventaire du cache et rend les clés effacées.
//
// Les clés sont retournées pour que l'appelant efface aussi les objets : vider
// la table seule laisserait des fichiers que plus rien ne référence, et que
// l'éviction ne trouverait donc jamais.
func (q *Queries) PurgeCacheEntries(ctx context.Context) ([]PurgeCacheEntriesRow, error) {
	rows, err := q.db.Query(ctx, purgeCacheEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurgeCacheEntriesRow{}
	for rows.Next() {
		var i PurgeCacheEntriesRow
		if err := rows.Scan(&i.Key, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCacheEntry = `-- name: RecordCacheEntry :exec

INSERT INTO cache_entries (key, comic_id, size)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
SET size = EXCLUDED.size, last_hit_at = now()
`

type RecordCacheEntryParams struct {
	Key     string
	ComicID uuid.NullUUID
	Size    int64
}

// ─── Cache dérivé ────────────────────────────────────────────────────────────
func (q *Queries) RecordCacheEntry(ctx context.Context, arg RecordCacheEntryParams) error {
	_, err := q.db.Exec(ctx, recordCacheEntry, arg.Key, arg.ComicID, arg.Size)
	return err
}

const refreshSeriesCounts = `-- name: RefreshSeriesCounts :exec
UPDATE series
SET comic_count = (
        -- Les albums retirés du catalogue à la demande ne comptent pas plus que
        -- ceux disparus du stockage : les deux sont invisibles de l'utilisateur.
        SELECT count(*) FROM comics
        WHERE comics.series_id = series.id
          AND comics.deleted_at IS NULL
          AND comics.excluded_at IS NULL
    ),
    cover_comic_id = coalesce(
        series.cover_comic_id,
        (SELECT comics.id FROM comics
         WHERE comics.series_id = series.id AND comics.deleted_at IS NULL
         ORDER BY comics.number_sort NULLS LAST, comics.title
         LIMIT 1)
    )
WHERE series.library_id = $1
`

func (q *Queries) RefreshSeriesCounts(ctx context.Context, libraryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, refreshSeriesCounts, libraryID)
	return err
}

const setComicHydrated = `-- name: SetComicHydrated :exec
UPDATE comics SET hydrated_key = $2 WHERE id = $1
`

type SetComicHydratedParams struct {
	ID          uuid.UUID
	HydratedKey *string
}

// Enregistre l'archive normalisée d'un album hydraté.
//
// Écrite AVANT l'indexation des pages : les offsets qui suivront désignent
// cette archive, et l'ordre inverse laisserait, en cas d'interruption, des
// pages pointant vers une archive que rien ne référence.
func (q *Queries) SetComicHydrated(ctx context.Context, arg SetComicHydratedParams) error {
	_, err := q.db.Exec(ctx, setComicHydrated, arg.ID, arg.HydratedKey)
	return err
}

const setComicIndexed = `-- name: SetComicIndexed :exec
UPDATE comics
SET state = 'ready',
    state_detail = NULL,
    page_count = $2,
    indexed_at = now()
WHERE id = $1
`

type SetComicIndexedParams struct {
	ID        uuid.UUID
	PageCount int32
}

func (q *Queries) SetComicIndexed(ctx context.Context, arg SetComicIndexedParams) error {
	_, err := q.db.Exec(ctx, setComicIndexed, arg.ID, arg.PageCount)
	return err
}

const setComicPlaceholder = `-- name: SetComicPlaceholder :exec
UPDATE comics SET cover_placeholder = $2 WHERE id = $1
`

type SetComicPlaceholderParams struct {
	ID               uuid.UUID
	CoverPlaceholder *string
}

func (q *Queries) SetComicPlaceholder(ctx context.Context, arg SetComicPlaceholderParams) error {
	_, err := q.db.Exec(ctx, setComicPlaceholder, arg.ID, arg.CoverPlaceholder)
	return err
}

const setComicState = `-- name: SetComicState :exec
UPDATE comics
SET state = $2, state_detail = $3
WHERE id = $1
`

type SetComicStateParams struct {
	ID          uuid.UUID
	State       ComicState
	StateDetail *string
}

func (q *Queries) SetComicState(ctx context.Context, arg SetComicStateParams) error {
	_, err := q.db.Exec(ctx, setComicState, arg.ID, arg.State, arg.StateDetail)
	return err
}

const totalCacheSize = `-- name: TotalCacheSize :one
SELECT coalesce(sum(size), 0)::bigint FROM cache_entries
`

func (q *Queries) TotalCacheSize(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, totalCacheSize)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const touchCacheEntry = `-- name: TouchCacheEntry :execrows
UPDATE cache_entries
SET last_hit_at = now(), hits = hits + 1
WHERE key = $1
`

func (q *Queries) TouchCacheEntry(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, touchCacheEntry, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertComic = `-- name: UpsertComic :one
INSERT INTO comics (
    id, library_id, object_key, file_size, file_etag, format, title, state
)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending')
ON CONFLICT (library_id, object_key) DO UPDATE
SET file_size  = EXCLUDED.file_size,
    file_etag  = EXCLUDED.file_etag,
    -- Un album retiré du catalogue à la demande le reste : le scan constate
    -- une présence, il n'annule pas une décision.
    deleted_at = CASE WHEN comics.excluded_at IS NOT NULL THEN comics.deleted_at ELSE NULL END,
    -- Un objet modifié doit être réindexé ; un objet inchangé garde son état.
    state = CASE
        WHEN comics.file_etag IS DISTINCT FROM EXCLUDED.file_etag
          OR comics.file_size <> EXCLUDED.file_size
        THEN 'pending'::comic_state
        ELSE comics.state
    END
RETURNING id, library_id, series_id, object_key, file_size, file_etag, content_hash, format, title, number, number_sort, volume, summary, released_at, age_rating, language, page_count, cover_page, state, state_detail, hydrated_at, indexed_at, metadata, locked_fields, created_at, updated_at, deleted_at, search_vector, cover_placeholder, folder_path, excluded_at, hydrated_key, (xmax = 0) AS inserted
`

type UpsertComicParams struct {
	ID        uuid.UUID
	LibraryID uuid.UUID
	ObjectKey string
	FileSize  int64
	FileEtag  *string
	Format    ComicFormat
	Title     string
}

type UpsertComicRow struct {
	ID               uuid.UUID
	LibraryID        uuid.UUID
	SeriesID         uuid.NullUUID
	ObjectKey        string
	FileSize         int64
	FileEtag         *string
	ContentHash      []byte
	Format           ComicFormat
	Title            string
	Number           *string
	NumberSort       pgtype.Numeric
	Volume           *int16
	Summary          *string
	ReleasedAt       pgtype.Date
	AgeRating        *int16
	Language         *string
	PageCount        int32
	CoverPage        int32
	State            ComicState
	StateDetail      *string
	HydratedAt       pgtype.Timestamptz
	IndexedAt        pgtype.Timestamptz
	Metadata         []byte
	LockedFields     []string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	SearchVector     interface{}
	CoverPlaceholder *string
	FolderPath       string
	ExcludedAt       pgtype.Timestamptz
	HydratedKey      *string
	Inserted         bool
}

// Ingestion idempotente : la clé naturelle (library_id, object_key) permet de
// rejouer un scan sans créer de doublon ni perdre les champs verrouillés.
func (q *Queries) UpsertComic(ctx context.Context, arg UpsertComicParams) (UpsertComicRow, error) {
	row := q.db.QueryRow(ctx, upsertComic,
		arg.ID,
		arg.LibraryID,
		arg.ObjectKey,
		arg.FileSize,
		arg.FileEtag,
		arg.Format,
		arg.Title,
	)
	var i UpsertComicRow
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.SeriesID,
		&i.ObjectKey,
		&i.FileSize,
		&i.FileEtag,
		&i.ContentHash,
		&i.Format,
		&i.Title,
		&i.Number,
		&i.NumberSort,
		&i.Volume,
		&i.Summary,
		&i.ReleasedAt,
		&i.AgeRating,
		&i.Language,
		&i.PageCount,
		&i.CoverPage,
		&i.State,
		&i.StateDetail,
		&i.HydratedAt,
		&i.IndexedAt,
		&i.Metadata,
		&i.LockedFields,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
		&i.CoverPlaceholder,
		&i.FolderPath,
		&i.ExcludedAt,
		&i.HydratedKey,
		&i.Inserted,
	)
	return i, err
}

const upsertSeries = `-- name: UpsertSeries :one

INSERT INTO series (id, library_id, name, sort_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (library_id, sort_name) DO UPDATE
SET name = EXCLUDED.name
RETURNING id, library_id, name, sort_name, description, publisher, status, age_rating, year_started, cover_comic_id, comic_count, metadata, locked_fields, created_at, updated_at
`

type UpsertSeriesParams struct {
	ID        uuid.UUID
	LibraryID uuid.UUID
	Name      string
	SortName  string
}

// ─── Séries ──────────────────────────────────────────────────────────────────
func (q *Queries) UpsertSeries(ctx context.Context, arg UpsertSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, upsertSeries,
		arg.ID,
		arg.LibraryID,
		arg.Name,
		arg.SortName,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Name,
		&i.SortName,
		&i.Description,
		&i.Publisher,
		&i.Status,
		&i.AgeRating,
		&i.YearStarted,
		&i.CoverComicID,
		&i.ComicCount,
		&i.Metadata,
		&i.LockedFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
