// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discovery.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDiscoveryImport = `-- name: CreateDiscoveryImport :one

INSERT INTO discovery_imports (
    id, source_id, source_name, href, library_id, folder, title, requested_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, source_id, source_name, href, library_id, folder, title, status, error_code, error_detail, comic_id, object_key, file_size, requested_by, created_at, started_at, finished_at
`

type CreateDiscoveryImportParams struct {
	ID          uuid.UUID
	SourceID    uuid.NullUUID
	SourceName  string
	Href        string
	LibraryID   uuid.UUID
	Folder      string
	Title       string
	RequestedBy uuid.NullUUID
}

// ─── Imports ─────────────────────────────────────────────────────────────────
func (q *Queries) CreateDiscoveryImport(ctx context.Context, arg CreateDiscoveryImportParams) (DiscoveryImport, error) {
	row := q.db.QueryRow(ctx, createDiscoveryImport,
		arg.ID,
		arg.SourceID,
		arg.SourceName,
		arg.Href,
		arg.LibraryID,
		arg.Folder,
		arg.Title,
		arg.RequestedBy,
	)
	var i DiscoveryImport
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceName,
		&i.Href,
		&i.LibraryID,
		&i.Folder,
		&i.Title,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.ComicID,
		&i.ObjectKey,
		&i.FileSize,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createDiscoverySource = `-- name: CreateDiscoverySource :one
INSERT INTO discovery_sources (id, name, url, kind, enabled, username, secret_enc, template)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, url, kind, enabled, username, secret_enc, last_error, last_checked_at, created_at, template
`

type CreateDiscoverySourceParams struct {
	ID        uuid.UUID
	Name      string
	URL       string
	Kind      string
	Enabled   bool
	Username  string
	SecretEnc []byte
	Template  []byte
}

func (q *Queries) CreateDiscoverySource(ctx context.Context, arg CreateDiscoverySourceParams) (DiscoverySource, error) {
	row := q.db.QueryRow(ctx, createDiscoverySource,
		arg.ID,
		arg.Name,
		arg.URL,
		arg.Kind,
		arg.Enabled,
		arg.Username,
		arg.SecretEnc,
		arg.Template,
	)
	var i DiscoverySource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.URL,
		&i.Kind,
		&i.Enabled,
		&i.Username,
		&i.SecretEnc,
		&i.LastError,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.Template,
	)
	return i, err
}

const deleteDiscoverySource = `-- name: DeleteDiscoverySource :exec
DELETE FROM discovery_sources WHERE id = $1
`

func (q *Queries) DeleteDiscoverySource(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDiscoverySource, id)
	return err
}

const enrichComic = `-- name: EnrichComic :one

UPDATE comics
SET summary = CASE
        WHEN nullif(summary, '') IS NULL AND NOT ('summary' = ANY(locked_fields))
        THEN coalesce($1, summary)
        ELSE summary END,
    language = CASE
        WHEN nullif(language, '') IS NULL AND NOT ('language' = ANY(locked_fields))
        THEN coalesce($2, language)
        ELSE language END
WHERE id = $3
RETURNING id, library_id, series_id, object_key, file_size, file_etag, content_hash, format, title, number, number_sort, volume, summary, released_at, age_rating, language, page_count, cover_page, state, state_detail, hydrated_at, indexed_at, metadata, locked_fields, created_at, updated_at, deleted_at, search_vector, cover_placeholder, folder_path, excluded_at, hydrated_key
`

type EnrichComicParams struct {
	Summary  *string
	Language *string
	ID       uuid.UUID
}

// ─── Enrichissement ──────────────────────────────────────────────────────────
// Complète un album avec une fiche de métadonnées.
//
// Trois garde-fous inscrits dans la requête plutôt que laissés au code.
//
// `nullif(champ, ”)` : seuls les champs VIDES sont remplis. Une fiche
// généraliste ne doit pas écraser ce que l'archive elle-même déclarait — le
// ComicInfo.xml d'un éditeur en sait plus sur son album qu'Open Library.
//
// `NOT (... = ANY(locked_fields))` : une saisie manuelle est intouchable. C'est
// la contrepartie de tout automatisme dans ce projet, et l'enrichissement n'y
// fait pas exception — corriger un titre à la main serait inutile s'il pouvait
// être défait par une requête vers un service tiers.
//
// `locked_fields` n'est PAS modifié : l'enrichissement est automatique, et
// verrouiller ce qu'il pose empêcherait une réindexation de le corriger avec
// une meilleure source.
func (q *Queries) EnrichComic(ctx context.Context, arg EnrichComicParams) (Comic, error) {
	row := q.db.QueryRow(ctx, enrichComic, arg.Summary, arg.Language, arg.ID)
	var i Comic
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.SeriesID,
		&i.ObjectKey,
		&i.FileSize,
		&i.FileEtag,
		&i.ContentHash,
		&i.Format,
		&i.Title,
		&i.Number,
		&i.NumberSort,
		&i.Volume,
		&i.Summary,
		&i.ReleasedAt,
		&i.AgeRating,
		&i.Language,
		&i.PageCount,
		&i.CoverPage,
		&i.State,
		&i.StateDetail,
		&i.HydratedAt,
		&i.IndexedAt,
		&i.Metadata,
		&i.LockedFields,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
		&i.CoverPlaceholder,
		&i.FolderPath,
		&i.ExcludedAt,
		&i.HydratedKey,
	)
	return i, err
}

const failDiscoveryImport = `-- name: FailDiscoveryImport :exec
UPDATE discovery_imports
SET status = 'failed',
    error_code = $2,
    error_detail = $3,
    finished_at = now()
WHERE id = $1
`

type FailDiscoveryImportParams struct {
	ID          uuid.UUID
	ErrorCode   string
	ErrorDetail string
}

func (q *Queries) FailDiscoveryImport(ctx context.Context, arg FailDiscoveryImportParams) error {
	_, err := q.db.Exec(ctx, failDiscoveryImport, arg.ID, arg.ErrorCode, arg.ErrorDetail)
	return err
}

const finishDiscoveryImport = `-- name: FinishDiscoveryImport :exec
UPDATE discovery_imports
SET status = 'done',
    comic_id = $2,
    object_key = $3,
    file_size = $4,
    error_code = '',
    error_detail = '',
    finished_at = now()
WHERE id = $1
`

type FinishDiscoveryImportParams struct {
	ID        uuid.UUID
	ComicID   uuid.NullUUID
	ObjectKey string
	FileSize  int64
}

func (q *Queries) FinishDiscoveryImport(ctx context.Context, arg FinishDiscoveryImportParams) error {
	_, err := q.db.Exec(ctx, finishDiscoveryImport,
		arg.ID,
		arg.ComicID,
		arg.ObjectKey,
		arg.FileSize,
	)
	return err
}

const getDiscoveryImport = `-- name: GetDiscoveryImport :one
SELECT id, source_id, source_name, href, library_id, folder, title, status, error_code, error_detail, comic_id, object_key, file_size, requested_by, created_at, started_at, finished_at FROM discovery_imports WHERE id = $1
`

func (q *Queries) GetDiscoveryImport(ctx context.Context, id uuid.UUID) (DiscoveryImport, error) {
	row := q.db.QueryRow(ctx, getDiscoveryImport, id)
	var i DiscoveryImport
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceName,
		&i.Href,
		&i.LibraryID,
		&i.Folder,
		&i.Title,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.ComicID,
		&i.ObjectKey,
		&i.FileSize,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getDiscoverySource = `-- name: GetDiscoverySource :one
SELECT id, name, url, kind, enabled, username, secret_enc, last_error, last_checked_at, created_at, template FROM discovery_sources WHERE id = $1
`

func (q *Queries) GetDiscoverySource(ctx context.Context, id uuid.UUID) (DiscoverySource, error) {
	row := q.db.QueryRow(ctx, getDiscoverySource, id)
	var i DiscoverySource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.URL,
		&i.Kind,
		&i.Enabled,
		&i.Username,
		&i.SecretEnc,
		&i.LastError,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.Template,
	)
	return i, err
}

const getDiscoverySourceSecret = `-- name: GetDiscoverySourceSecret :one
SELECT secret_enc FROM discovery_sources WHERE id = $1
`

// Le secret est lu seul, par une requête distincte.
//
// Ce n'est pas une contrainte technique : `GetDiscoverySource` le rapporte déjà.
// C'est une contrainte de lecture. Un développeur qui écrit un gestionnaire voit
// qu'il faut une deuxième requête pour obtenir le mot de passe, ce qui rend
// difficile de le laisser filer dans une réponse par distraction.
func (q *Queries) GetDiscoverySourceSecret(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDiscoverySourceSecret, id)
	var secret_enc []byte
	err := row.Scan(&secret_enc)
	return secret_enc, err
}

const listDiscoveryImports = `-- name: ListDiscoveryImports :many
SELECT id, source_id, source_name, href, library_id, folder, title, status, error_code, error_detail, comic_id, object_key, file_size, requested_by, created_at, started_at, finished_at FROM discovery_imports
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListDiscoveryImports(ctx context.Context, limit int32) ([]DiscoveryImport, error) {
	rows, err := q.db.Query(ctx, listDiscoveryImports, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoveryImport{}
	for rows.Next() {
		var i DiscoveryImport
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.SourceName,
			&i.Href,
			&i.LibraryID,
			&i.Folder,
			&i.Title,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorDetail,
			&i.ComicID,
			&i.ObjectKey,
			&i.FileSize,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoverySources = `-- name: ListDiscoverySources :many
SELECT id, name, url, kind, enabled, username, secret_enc, last_error, last_checked_at, created_at, template FROM discovery_sources ORDER BY name
`

func (q *Queries) ListDiscoverySources(ctx context.Context) ([]DiscoverySource, error) {
	rows, err := q.db.Query(ctx, listDiscoverySources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoverySource{}
	for rows.Next() {
		var i DiscoverySource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.URL,
			&i.Kind,
			&i.Enabled,
			&i.Username,
			&i.SecretEnc,
			&i.LastError,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.Template,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDiscoveryProbe = `-- name: RecordDiscoveryProbe :exec
UPDATE discovery_sources
SET last_error = $2,
    last_checked_at = now()
WHERE id = $1
`

type RecordDiscoveryProbeParams struct {
	ID        uuid.UUID
	LastError string
}

func (q *Queries) RecordDiscoveryProbe(ctx context.Context, arg RecordDiscoveryProbeParams) error {
	_, err := q.db.Exec(ctx, recordDiscoveryProbe, arg.ID, arg.LastError)
	return err
}

const startDiscoveryImport = `-- name: StartDiscoveryImport :exec
UPDATE discovery_imports
SET status = 'running', started_at = now()
WHERE id = $1
`

func (q *Queries) StartDiscoveryImport(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, startDiscoveryImport, id)
	return err
}

const updateDiscoverySource = `-- name: UpdateDiscoverySource :one
UPDATE discovery_sources
SET name     = $2,
    url      = $3,
    enabled  = $4,
    username = $5,
    -- Les règles d'extraction ne se vident pas : une source ` + "`" + `web` + "`" + ` sans elles
    -- serait interrogée sans qu'on sache quoi lire, et la contrainte de la base
    -- refuserait la ligne. Ne pas les envoyer conserve celles en place.
    template = COALESCE($6::jsonb, template),
    -- Le mot de passe n'est remplacé que si l'appelant le demande : un
    -- formulaire qui renvoie un champ vide ne doit pas effacer ce qui marche.
    secret_enc = CASE WHEN $7::boolean
                      THEN $8::bytea
                      ELSE secret_enc END
WHERE id = $1
RETURNING id, name, url, kind, enabled, username, secret_enc, last_error, last_checked_at, created_at, template
`

type UpdateDiscoverySourceParams struct {
	ID            uuid.UUID
	Name          string
	URL           string
	Enabled       bool
	Username      string
	Template      []byte
	ReplaceSecret bool
	SecretEnc     []byte
}

func (q *Queries) UpdateDiscoverySource(ctx context.Context, arg UpdateDiscoverySourceParams) (DiscoverySource, error) {
	row := q.db.QueryRow(ctx, updateDiscoverySource,
		arg.ID,
		arg.Name,
		arg.URL,
		arg.Enabled,
		arg.Username,
		arg.Template,
		arg.ReplaceSecret,
		arg.SecretEnc,
	)
	var i DiscoverySource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.URL,
		&i.Kind,
		&i.Enabled,
		&i.Username,
		&i.SecretEnc,
		&i.LastError,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.Template,
	)
	return i, err
}
