// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discovery.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDiscoverySource = `-- name: CreateDiscoverySource :one
INSERT INTO discovery_sources (id, name, url, kind, enabled, username, secret_enc)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, url, kind, enabled, username, secret_enc, last_error, last_checked_at, created_at
`

type CreateDiscoverySourceParams struct {
	ID        uuid.UUID
	Name      string
	URL       string
	Kind      string
	Enabled   bool
	Username  string
	SecretEnc []byte
}

func (q *Queries) CreateDiscoverySource(ctx context.Context, arg CreateDiscoverySourceParams) (DiscoverySource, error) {
	row := q.db.QueryRow(ctx, createDiscoverySource,
		arg.ID,
		arg.Name,
		arg.URL,
		arg.Kind,
		arg.Enabled,
		arg.Username,
		arg.SecretEnc,
	)
	var i DiscoverySource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.URL,
		&i.Kind,
		&i.Enabled,
		&i.Username,
		&i.SecretEnc,
		&i.LastError,
		&i.LastCheckedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDiscoverySource = `-- name: DeleteDiscoverySource :exec
DELETE FROM discovery_sources WHERE id = $1
`

func (q *Queries) DeleteDiscoverySource(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDiscoverySource, id)
	return err
}

const getDiscoverySource = `-- name: GetDiscoverySource :one
SELECT id, name, url, kind, enabled, username, secret_enc, last_error, last_checked_at, created_at FROM discovery_sources WHERE id = $1
`

func (q *Queries) GetDiscoverySource(ctx context.Context, id uuid.UUID) (DiscoverySource, error) {
	row := q.db.QueryRow(ctx, getDiscoverySource, id)
	var i DiscoverySource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.URL,
		&i.Kind,
		&i.Enabled,
		&i.Username,
		&i.SecretEnc,
		&i.LastError,
		&i.LastCheckedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDiscoverySourceSecret = `-- name: GetDiscoverySourceSecret :one
SELECT secret_enc FROM discovery_sources WHERE id = $1
`

// Le secret est lu seul, par une requête distincte.
//
// Ce n'est pas une contrainte technique : `GetDiscoverySource` le rapporte déjà.
// C'est une contrainte de lecture. Un développeur qui écrit un gestionnaire voit
// qu'il faut une deuxième requête pour obtenir le mot de passe, ce qui rend
// difficile de le laisser filer dans une réponse par distraction.
func (q *Queries) GetDiscoverySourceSecret(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDiscoverySourceSecret, id)
	var secret_enc []byte
	err := row.Scan(&secret_enc)
	return secret_enc, err
}

const listDiscoverySources = `-- name: ListDiscoverySources :many
SELECT id, name, url, kind, enabled, username, secret_enc, last_error, last_checked_at, created_at FROM discovery_sources ORDER BY name
`

func (q *Queries) ListDiscoverySources(ctx context.Context) ([]DiscoverySource, error) {
	rows, err := q.db.Query(ctx, listDiscoverySources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoverySource{}
	for rows.Next() {
		var i DiscoverySource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.URL,
			&i.Kind,
			&i.Enabled,
			&i.Username,
			&i.SecretEnc,
			&i.LastError,
			&i.LastCheckedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDiscoveryProbe = `-- name: RecordDiscoveryProbe :exec
UPDATE discovery_sources
SET last_error = $2,
    last_checked_at = now()
WHERE id = $1
`

type RecordDiscoveryProbeParams struct {
	ID        uuid.UUID
	LastError string
}

func (q *Queries) RecordDiscoveryProbe(ctx context.Context, arg RecordDiscoveryProbeParams) error {
	_, err := q.db.Exec(ctx, recordDiscoveryProbe, arg.ID, arg.LastError)
	return err
}

const updateDiscoverySource = `-- name: UpdateDiscoverySource :one
UPDATE discovery_sources
SET name     = $2,
    url      = $3,
    enabled  = $4,
    username = $5,
    -- Le mot de passe n'est remplacé que si l'appelant le demande : un
    -- formulaire qui renvoie un champ vide ne doit pas effacer ce qui marche.
    secret_enc = CASE WHEN $6::boolean
                      THEN $7::bytea
                      ELSE secret_enc END
WHERE id = $1
RETURNING id, name, url, kind, enabled, username, secret_enc, last_error, last_checked_at, created_at
`

type UpdateDiscoverySourceParams struct {
	ID            uuid.UUID
	Name          string
	URL           string
	Enabled       bool
	Username      string
	ReplaceSecret bool
	SecretEnc     []byte
}

func (q *Queries) UpdateDiscoverySource(ctx context.Context, arg UpdateDiscoverySourceParams) (DiscoverySource, error) {
	row := q.db.QueryRow(ctx, updateDiscoverySource,
		arg.ID,
		arg.Name,
		arg.URL,
		arg.Enabled,
		arg.Username,
		arg.ReplaceSecret,
		arg.SecretEnc,
	)
	var i DiscoverySource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.URL,
		&i.Kind,
		&i.Enabled,
		&i.Username,
		&i.SecretEnc,
		&i.LastError,
		&i.LastCheckedAt,
		&i.CreatedAt,
	)
	return i, err
}
