// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ed2k_destinations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const claimEd2kPublication = `-- name: ClaimEd2kPublication :one
INSERT INTO ed2k_publications (hash, name, size, category, status)
VALUES ($1, $2, $3, $4, 'pending')
ON CONFLICT (hash) DO NOTHING
RETURNING hash, name, size, category, library_id, comic_id, status, detail, created_at, updated_at
`

type ClaimEd2kPublicationParams struct {
	Hash     string
	Name     string
	Size     int64
	Category int32
}

// Réserve une publication.
//
// L'insertion échoue si l'empreinte est déjà connue : c'est ce qui rend le pont
// idempotent sans verrou. Deux tours de scrutation qui verraient le même
// fichier terminé ne produiront qu'une publication.
func (q *Queries) ClaimEd2kPublication(ctx context.Context, arg ClaimEd2kPublicationParams) (Ed2kPublication, error) {
	row := q.db.QueryRow(ctx, claimEd2kPublication,
		arg.Hash,
		arg.Name,
		arg.Size,
		arg.Category,
	)
	var i Ed2kPublication
	err := row.Scan(
		&i.Hash,
		&i.Name,
		&i.Size,
		&i.Category,
		&i.LibraryID,
		&i.ComicID,
		&i.Status,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEd2kDestination = `-- name: DeleteEd2kDestination :exec
DELETE FROM ed2k_destinations WHERE category = $1
`

func (q *Queries) DeleteEd2kDestination(ctx context.Context, category int32) error {
	_, err := q.db.Exec(ctx, deleteEd2kDestination, category)
	return err
}

const getEd2kDestination = `-- name: GetEd2kDestination :one
SELECT category, label, library_id, folder, created_at, updated_at FROM ed2k_destinations WHERE category = $1
`

func (q *Queries) GetEd2kDestination(ctx context.Context, category int32) (Ed2kDestination, error) {
	row := q.db.QueryRow(ctx, getEd2kDestination, category)
	var i Ed2kDestination
	err := row.Scan(
		&i.Category,
		&i.Label,
		&i.LibraryID,
		&i.Folder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEd2kPublication = `-- name: GetEd2kPublication :one

SELECT hash, name, size, category, library_id, comic_id, status, detail, created_at, updated_at FROM ed2k_publications WHERE hash = $1
`

// Publications : le journal du pont, et la garantie de ne rien publier deux fois.
func (q *Queries) GetEd2kPublication(ctx context.Context, hash string) (Ed2kPublication, error) {
	row := q.db.QueryRow(ctx, getEd2kPublication, hash)
	var i Ed2kPublication
	err := row.Scan(
		&i.Hash,
		&i.Name,
		&i.Size,
		&i.Category,
		&i.LibraryID,
		&i.ComicID,
		&i.Status,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEd2kDestinations = `-- name: ListEd2kDestinations :many

SELECT category, label, library_id, folder, created_at, updated_at FROM ed2k_destinations ORDER BY category
`

// Destinations : ce que devient un fichier terminé, selon sa catégorie.
func (q *Queries) ListEd2kDestinations(ctx context.Context) ([]Ed2kDestination, error) {
	rows, err := q.db.Query(ctx, listEd2kDestinations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ed2kDestination{}
	for rows.Next() {
		var i Ed2kDestination
		if err := rows.Scan(
			&i.Category,
			&i.Label,
			&i.LibraryID,
			&i.Folder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEd2kPublications = `-- name: ListEd2kPublications :many
SELECT hash, name, size, category, library_id, comic_id, status, detail, created_at, updated_at FROM ed2k_publications ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListEd2kPublications(ctx context.Context, limit int32) ([]Ed2kPublication, error) {
	rows, err := q.db.Query(ctx, listEd2kPublications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ed2kPublication{}
	for rows.Next() {
		var i Ed2kPublication
		if err := rows.Scan(
			&i.Hash,
			&i.Name,
			&i.Size,
			&i.Category,
			&i.LibraryID,
			&i.ComicID,
			&i.Status,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEd2kPublicationResult = `-- name: SetEd2kPublicationResult :exec
UPDATE ed2k_publications
SET status     = $1,
    detail     = $2,
    library_id = $3,
    comic_id   = $4
WHERE hash = $5
`

type SetEd2kPublicationResultParams struct {
	Status    string
	Detail    *string
	LibraryID uuid.NullUUID
	ComicID   uuid.NullUUID
	Hash      string
}

func (q *Queries) SetEd2kPublicationResult(ctx context.Context, arg SetEd2kPublicationResultParams) error {
	_, err := q.db.Exec(ctx, setEd2kPublicationResult,
		arg.Status,
		arg.Detail,
		arg.LibraryID,
		arg.ComicID,
		arg.Hash,
	)
	return err
}

const upsertEd2kDestination = `-- name: UpsertEd2kDestination :one
INSERT INTO ed2k_destinations (category, label, library_id, folder)
VALUES ($1, $2, $3, $4)
ON CONFLICT (category) DO UPDATE
    SET label      = EXCLUDED.label,
        library_id = EXCLUDED.library_id,
        folder     = EXCLUDED.folder
RETURNING category, label, library_id, folder, created_at, updated_at
`

type UpsertEd2kDestinationParams struct {
	Category  int32
	Label     string
	LibraryID uuid.NullUUID
	Folder    string
}

func (q *Queries) UpsertEd2kDestination(ctx context.Context, arg UpsertEd2kDestinationParams) (Ed2kDestination, error) {
	row := q.db.QueryRow(ctx, upsertEd2kDestination,
		arg.Category,
		arg.Label,
		arg.LibraryID,
		arg.Folder,
	)
	var i Ed2kDestination
	err := row.Scan(
		&i.Category,
		&i.Label,
		&i.LibraryID,
		&i.Folder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
