// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ed2k.sql

package sqlc

import (
	"context"
)

const deleteEd2kDaemon = `-- name: DeleteEd2kDaemon :exec
DELETE FROM ed2k_daemon WHERE id
`

func (q *Queries) DeleteEd2kDaemon(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteEd2kDaemon)
	return err
}

const getEd2kDaemon = `-- name: GetEd2kDaemon :one

SELECT id, host, port, password_enc, label, last_state, last_detail, last_seen_at, created_at, updated_at FROM ed2k_daemon WHERE id
`

// Module eD2k/Kad — connexion au démon aMule.
//
// La ligne est unique par construction (CHECK (id) dans la migration), ce qui
// permet à toutes ces requêtes de se passer de clé : il n'y a rien à désigner.
func (q *Queries) GetEd2kDaemon(ctx context.Context) (Ed2kDaemon, error) {
	row := q.db.QueryRow(ctx, getEd2kDaemon)
	var i Ed2kDaemon
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Port,
		&i.PasswordEnc,
		&i.Label,
		&i.LastState,
		&i.LastDetail,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setEd2kDaemonState = `-- name: SetEd2kDaemonState :exec
UPDATE ed2k_daemon
SET last_state   = $1,
    last_detail  = $2,
    -- ` + "`" + `seen` + "`" + ` n'est vrai que si le démon a effectivement répondu : un échec ne
    -- doit pas rafraîchir la date de dernier contact, sinon l'interface
    -- affiche « vu à l'instant » pour un démon injoignable depuis une heure.
    last_seen_at = CASE WHEN $3::boolean THEN now() ELSE last_seen_at END
WHERE id
`

type SetEd2kDaemonStateParams struct {
	State  *string
	Detail *string
	Seen   bool
}

// Écrit le dernier état constaté sans toucher aux identifiants.
//
// Séparée de l'upsert délibérément : la boucle de scrutation met cet état à
// jour, et elle n'a aucune raison de pouvoir réécrire un mot de passe.
func (q *Queries) SetEd2kDaemonState(ctx context.Context, arg SetEd2kDaemonStateParams) error {
	_, err := q.db.Exec(ctx, setEd2kDaemonState, arg.State, arg.Detail, arg.Seen)
	return err
}

const upsertEd2kDaemon = `-- name: UpsertEd2kDaemon :one
INSERT INTO ed2k_daemon (id, host, port, password_enc, label)
VALUES (true, $1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
    SET host         = EXCLUDED.host,
        port         = EXCLUDED.port,
        password_enc = EXCLUDED.password_enc,
        label        = EXCLUDED.label
RETURNING id, host, port, password_enc, label, last_state, last_detail, last_seen_at, created_at, updated_at
`

type UpsertEd2kDaemonParams struct {
	Host        string
	Port        int32
	PasswordEnc []byte
	Label       *string
}

func (q *Queries) UpsertEd2kDaemon(ctx context.Context, arg UpsertEd2kDaemonParams) (Ed2kDaemon, error) {
	row := q.db.QueryRow(ctx, upsertEd2kDaemon,
		arg.Host,
		arg.Port,
		arg.PasswordEnc,
		arg.Label,
	)
	var i Ed2kDaemon
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Port,
		&i.PasswordEnc,
		&i.Label,
		&i.LastState,
		&i.LastDetail,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
