// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: libraries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countLibrariesUsingBackend = `-- name: CountLibrariesUsingBackend :one
SELECT count(*) FROM libraries WHERE storage_backend_id = $1
`

// Combien de bibliothèques s'appuient sur ce backend ?
//
// Sert à refuser sa suppression tant qu'il en porte : effacer un backend
// emporterait ses bibliothèques par cascade, et avec elles la progression de
// lecture de tout le monde.
func (q *Queries) CountLibrariesUsingBackend(ctx context.Context, storageBackendID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLibrariesUsingBackend, storageBackendID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLibrary = `-- name: CreateLibrary :one
INSERT INTO libraries (id, storage_backend_id, name, kind, root_prefix, scan_options, scan_cron)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, storage_backend_id, name, kind, root_prefix, scan_options, scan_cron, last_scan_at, last_scan_status, comic_count, created_at, updated_at
`

type CreateLibraryParams struct {
	ID               uuid.UUID
	StorageBackendID uuid.UUID
	Name             string
	Kind             LibraryKind
	RootPrefix       string
	ScanOptions      []byte
	ScanCron         *string
}

func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error) {
	row := q.db.QueryRow(ctx, createLibrary,
		arg.ID,
		arg.StorageBackendID,
		arg.Name,
		arg.Kind,
		arg.RootPrefix,
		arg.ScanOptions,
		arg.ScanCron,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.StorageBackendID,
		&i.Name,
		&i.Kind,
		&i.RootPrefix,
		&i.ScanOptions,
		&i.ScanCron,
		&i.LastScanAt,
		&i.LastScanStatus,
		&i.ComicCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLibrary = `-- name: DeleteLibrary :exec
DELETE FROM libraries WHERE id = $1
`

func (q *Queries) DeleteLibrary(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLibrary, id)
	return err
}

const finishScanRun = `-- name: FinishScanRun :exec
UPDATE scan_runs
SET finished_at = now(),
    status = $2,
    objects_seen = $3,
    added = $4,
    updated = $5,
    removed = $6,
    errors = $7,
    detail = $8
WHERE id = $1
`

type FinishScanRunParams struct {
	ID          uuid.UUID
	Status      string
	ObjectsSeen int32
	Added       int32
	Updated     int32
	Removed     int32
	Errors      int32
	Detail      []byte
}

func (q *Queries) FinishScanRun(ctx context.Context, arg FinishScanRunParams) error {
	_, err := q.db.Exec(ctx, finishScanRun,
		arg.ID,
		arg.Status,
		arg.ObjectsSeen,
		arg.Added,
		arg.Updated,
		arg.Removed,
		arg.Errors,
		arg.Detail,
	)
	return err
}

const getLibrary = `-- name: GetLibrary :one
SELECT id, storage_backend_id, name, kind, root_prefix, scan_options, scan_cron, last_scan_at, last_scan_status, comic_count, created_at, updated_at FROM libraries WHERE id = $1
`

func (q *Queries) GetLibrary(ctx context.Context, id uuid.UUID) (Library, error) {
	row := q.db.QueryRow(ctx, getLibrary, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.StorageBackendID,
		&i.Name,
		&i.Kind,
		&i.RootPrefix,
		&i.ScanOptions,
		&i.ScanCron,
		&i.LastScanAt,
		&i.LastScanStatus,
		&i.ComicCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLibraryByName = `-- name: GetLibraryByName :one
SELECT id, storage_backend_id, name, kind, root_prefix, scan_options, scan_cron, last_scan_at, last_scan_status, comic_count, created_at, updated_at FROM libraries WHERE name = $1
`

func (q *Queries) GetLibraryByName(ctx context.Context, name string) (Library, error) {
	row := q.db.QueryRow(ctx, getLibraryByName, name)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.StorageBackendID,
		&i.Name,
		&i.Kind,
		&i.RootPrefix,
		&i.ScanOptions,
		&i.ScanCron,
		&i.LastScanAt,
		&i.LastScanStatus,
		&i.ComicCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScanRun = `-- name: GetScanRun :one
SELECT id, library_id, started_at, finished_at, status, objects_seen, added, updated, removed, errors, cursor, detail FROM scan_runs WHERE id = $1
`

func (q *Queries) GetScanRun(ctx context.Context, id uuid.UUID) (ScanRun, error) {
	row := q.db.QueryRow(ctx, getScanRun, id)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.ObjectsSeen,
		&i.Added,
		&i.Updated,
		&i.Removed,
		&i.Errors,
		&i.Cursor,
		&i.Detail,
	)
	return i, err
}

const listLibraries = `-- name: ListLibraries :many
SELECT id, storage_backend_id, name, kind, root_prefix, scan_options, scan_cron, last_scan_at, last_scan_status, comic_count, created_at, updated_at FROM libraries ORDER BY name
`

func (q *Queries) ListLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.db.Query(ctx, listLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Library{}
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.StorageBackendID,
			&i.Name,
			&i.Kind,
			&i.RootPrefix,
			&i.ScanOptions,
			&i.ScanCron,
			&i.LastScanAt,
			&i.LastScanStatus,
			&i.ComicCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibrariesWithBackend = `-- name: ListLibrariesWithBackend :many
SELECT
    libraries.id, libraries.storage_backend_id, libraries.name, libraries.kind, libraries.root_prefix, libraries.scan_options, libraries.scan_cron, libraries.last_scan_at, libraries.last_scan_status, libraries.comic_count, libraries.created_at, libraries.updated_at,
    storage_backends.id, storage_backends.name, storage_backends.kind, storage_backends.config, storage_backends.secrets_enc, storage_backends.is_default, storage_backends.read_only, storage_backends.status, storage_backends.status_detail, storage_backends.checked_at, storage_backends.created_at, storage_backends.updated_at
FROM libraries
JOIN storage_backends ON storage_backends.id = libraries.storage_backend_id
ORDER BY libraries.name
`

type ListLibrariesWithBackendRow struct {
	Library        Library
	StorageBackend StorageBackend
}

func (q *Queries) ListLibrariesWithBackend(ctx context.Context) ([]ListLibrariesWithBackendRow, error) {
	rows, err := q.db.Query(ctx, listLibrariesWithBackend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLibrariesWithBackendRow{}
	for rows.Next() {
		var i ListLibrariesWithBackendRow
		if err := rows.Scan(
			&i.Library.ID,
			&i.Library.StorageBackendID,
			&i.Library.Name,
			&i.Library.Kind,
			&i.Library.RootPrefix,
			&i.Library.ScanOptions,
			&i.Library.ScanCron,
			&i.Library.LastScanAt,
			&i.Library.LastScanStatus,
			&i.Library.ComicCount,
			&i.Library.CreatedAt,
			&i.Library.UpdatedAt,
			&i.StorageBackend.ID,
			&i.StorageBackend.Name,
			&i.StorageBackend.Kind,
			&i.StorageBackend.Config,
			&i.StorageBackend.SecretsEnc,
			&i.StorageBackend.IsDefault,
			&i.StorageBackend.ReadOnly,
			&i.StorageBackend.Status,
			&i.StorageBackend.StatusDetail,
			&i.StorageBackend.CheckedAt,
			&i.StorageBackend.CreatedAt,
			&i.StorageBackend.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanRuns = `-- name: ListScanRuns :many
SELECT id, library_id, started_at, finished_at, status, objects_seen, added, updated, removed, errors, cursor, detail FROM scan_runs
WHERE library_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListScanRunsParams struct {
	LibraryID uuid.UUID
	Limit     int32
}

func (q *Queries) ListScanRuns(ctx context.Context, arg ListScanRunsParams) ([]ScanRun, error) {
	rows, err := q.db.Query(ctx, listScanRuns, arg.LibraryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanRun{}
	for rows.Next() {
		var i ScanRun
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.ObjectsSeen,
			&i.Added,
			&i.Updated,
			&i.Removed,
			&i.Errors,
			&i.Cursor,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshLibraryCount = `-- name: RefreshLibraryCount :exec
UPDATE libraries
SET comic_count = (
        SELECT count(*) FROM comics
        WHERE comics.library_id = $1
          AND comics.deleted_at IS NULL
          AND comics.excluded_at IS NULL
    )
WHERE libraries.id = $1
`

// Recompte les albums d'une bibliothèque.
//
// Le compteur est une colonne stockée, et il ne l'était rafraîchi qu'en fin de
// parcours. Supprimer un album le laissait donc figé : la barre latérale
// annonçait vingt-et-un albums devant une grille vide, jusqu'au prochain scan.
//
// Les deux dates comptent. `deleted_at` marque un objet disparu du backend,
// `excluded_at` un album retiré du catalogue par l'utilisateur. Le premier
// filtre était seul, si bien qu'un retrait sans suppression de fichier ne
// décrémentait rien — même après un scan.
func (q *Queries) RefreshLibraryCount(ctx context.Context, libraryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, refreshLibraryCount, libraryID)
	return err
}

const setLibraryScanResult = `-- name: SetLibraryScanResult :exec
UPDATE libraries
SET last_scan_at = now(),
    last_scan_status = $2,
    comic_count = (
        SELECT count(*) FROM comics
        WHERE comics.library_id = $1
          AND comics.deleted_at IS NULL
          AND comics.excluded_at IS NULL
    )
WHERE libraries.id = $1
`

type SetLibraryScanResultParams struct {
	LibraryID      uuid.UUID
	LastScanStatus *string
}

func (q *Queries) SetLibraryScanResult(ctx context.Context, arg SetLibraryScanResultParams) error {
	_, err := q.db.Exec(ctx, setLibraryScanResult, arg.LibraryID, arg.LastScanStatus)
	return err
}

const startScanRun = `-- name: StartScanRun :one

INSERT INTO scan_runs (id, library_id)
VALUES ($1, $2)
RETURNING id, library_id, started_at, finished_at, status, objects_seen, added, updated, removed, errors, cursor, detail
`

type StartScanRunParams struct {
	ID        uuid.UUID
	LibraryID uuid.UUID
}

// ─── Scans ───────────────────────────────────────────────────────────────────
func (q *Queries) StartScanRun(ctx context.Context, arg StartScanRunParams) (ScanRun, error) {
	row := q.db.QueryRow(ctx, startScanRun, arg.ID, arg.LibraryID)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.ObjectsSeen,
		&i.Added,
		&i.Updated,
		&i.Removed,
		&i.Errors,
		&i.Cursor,
		&i.Detail,
	)
	return i, err
}

const updateLibrary = `-- name: UpdateLibrary :one

UPDATE libraries
SET name        = coalesce($2, name),
    root_prefix = coalesce($3, root_prefix)
WHERE id = $1
RETURNING id, storage_backend_id, name, kind, root_prefix, scan_options, scan_cron, last_scan_at, last_scan_status, comic_count, created_at, updated_at
`

type UpdateLibraryParams struct {
	ID         uuid.UUID
	Name       *string
	RootPrefix *string
}

// ─── Administration ──────────────────────────────────────────────────────────
func (q *Queries) UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (Library, error) {
	row := q.db.QueryRow(ctx, updateLibrary, arg.ID, arg.Name, arg.RootPrefix)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.StorageBackendID,
		&i.Name,
		&i.Kind,
		&i.RootPrefix,
		&i.ScanOptions,
		&i.ScanCron,
		&i.LastScanAt,
		&i.LastScanStatus,
		&i.ComicCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
