// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ComicFormat string

const (
	ComicFormatCbz  ComicFormat = "cbz"
	ComicFormatCbr  ComicFormat = "cbr"
	ComicFormatCb7  ComicFormat = "cb7"
	ComicFormatPdf  ComicFormat = "pdf"
	ComicFormatEpub ComicFormat = "epub"
)

func (e *ComicFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ComicFormat(s)
	case string:
		*e = ComicFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for ComicFormat: %T", src)
	}
	return nil
}

type NullComicFormat struct {
	ComicFormat ComicFormat
	Valid       bool // Valid is true if ComicFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullComicFormat) Scan(value interface{}) error {
	if value == nil {
		ns.ComicFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ComicFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullComicFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ComicFormat), nil
}

type ComicState string

const (
	ComicStatePending   ComicState = "pending"
	ComicStateIndexing  ComicState = "indexing"
	ComicStateReady     ComicState = "ready"
	ComicStateHydrating ComicState = "hydrating"
	ComicStateError     ComicState = "error"
)

func (e *ComicState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ComicState(s)
	case string:
		*e = ComicState(s)
	default:
		return fmt.Errorf("unsupported scan type for ComicState: %T", src)
	}
	return nil
}

type NullComicState struct {
	ComicState ComicState
	Valid      bool // Valid is true if ComicState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullComicState) Scan(value interface{}) error {
	if value == nil {
		ns.ComicState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ComicState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullComicState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ComicState), nil
}

type DevicePlatform string

const (
	DevicePlatformWeb     DevicePlatform = "web"
	DevicePlatformAndroid DevicePlatform = "android"
	DevicePlatformIos     DevicePlatform = "ios"
	DevicePlatformDesktop DevicePlatform = "desktop"
	DevicePlatformUnknown DevicePlatform = "unknown"
)

func (e *DevicePlatform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DevicePlatform(s)
	case string:
		*e = DevicePlatform(s)
	default:
		return fmt.Errorf("unsupported scan type for DevicePlatform: %T", src)
	}
	return nil
}

type NullDevicePlatform struct {
	DevicePlatform DevicePlatform
	Valid          bool // Valid is true if DevicePlatform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDevicePlatform) Scan(value interface{}) error {
	if value == nil {
		ns.DevicePlatform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DevicePlatform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDevicePlatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DevicePlatform), nil
}

type LibraryKind string

const (
	LibraryKindComic LibraryKind = "comic"
	LibraryKindManga LibraryKind = "manga"
	LibraryKindBook  LibraryKind = "book"
	LibraryKindMixed LibraryKind = "mixed"
)

func (e *LibraryKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LibraryKind(s)
	case string:
		*e = LibraryKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LibraryKind: %T", src)
	}
	return nil
}

type NullLibraryKind struct {
	LibraryKind LibraryKind
	Valid       bool // Valid is true if LibraryKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLibraryKind) Scan(value interface{}) error {
	if value == nil {
		ns.LibraryKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LibraryKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLibraryKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LibraryKind), nil
}

type ReadStatus string

const (
	ReadStatusUnread     ReadStatus = "unread"
	ReadStatusInProgress ReadStatus = "in_progress"
	ReadStatusRead       ReadStatus = "read"
)

func (e *ReadStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReadStatus(s)
	case string:
		*e = ReadStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReadStatus: %T", src)
	}
	return nil
}

type NullReadStatus struct {
	ReadStatus ReadStatus
	Valid      bool // Valid is true if ReadStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReadStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReadStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReadStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReadStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReadStatus), nil
}

type StorageKind string

const (
	StorageKindS3     StorageKind = "s3"
	StorageKindLocal  StorageKind = "local"
	StorageKindWebdav StorageKind = "webdav"
)

func (e *StorageKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StorageKind(s)
	case string:
		*e = StorageKind(s)
	default:
		return fmt.Errorf("unsupported scan type for StorageKind: %T", src)
	}
	return nil
}

type NullStorageKind struct {
	StorageKind StorageKind
	Valid       bool // Valid is true if StorageKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStorageKind) Scan(value interface{}) error {
	if value == nil {
		ns.StorageKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StorageKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStorageKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StorageKind), nil
}

type StorageStatus string

const (
	StorageStatusOk        StorageStatus = "ok"
	StorageStatusDegraded  StorageStatus = "degraded"
	StorageStatusError     StorageStatus = "error"
	StorageStatusUnchecked StorageStatus = "unchecked"
)

func (e *StorageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StorageStatus(s)
	case string:
		*e = StorageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StorageStatus: %T", src)
	}
	return nil
}

type NullStorageStatus struct {
	StorageStatus StorageStatus
	Valid         bool // Valid is true if StorageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStorageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StorageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StorageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStorageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StorageStatus), nil
}

type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type APIKey struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	KeyHash    []byte
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type CacheEntry struct {
	Key       string
	ComicID   uuid.NullUUID
	Size      int64
	LastHitAt pgtype.Timestamptz
	Hits      int32
	CreatedAt pgtype.Timestamptz
}

type Comic struct {
	ID           uuid.UUID
	LibraryID    uuid.UUID
	SeriesID     uuid.NullUUID
	ObjectKey    string
	FileSize     int64
	FileEtag     *string
	ContentHash  []byte
	Format       ComicFormat
	Title        string
	Number       *string
	NumberSort   pgtype.Numeric
	Volume       *int16
	Summary      *string
	ReleasedAt   pgtype.Date
	AgeRating    *int16
	Language     *string
	PageCount    int32
	CoverPage    int32
	State        ComicState
	StateDetail  *string
	HydratedAt   pgtype.Timestamptz
	IndexedAt    pgtype.Timestamptz
	Metadata     []byte
	LockedFields []string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	SearchVector interface{}
	// Data-URI d'une miniature JPEG de ~16px, affichée floutée pendant le chargement.
	CoverPlaceholder *string
	// Dossier contenant l'album, relatif au préfixe de la bibliothèque. Vide à la racine.
	FolderPath string
	// Retiré du catalogue à la demande. Le scan ne le fait pas réapparaître.
	ExcludedAt pgtype.Timestamptz
}

type ComicPage struct {
	ComicID     uuid.UUID
	Index       int32
	EntryName   string
	DataOffset  *int64
	DataSize    *int64
	Size        *int64
	Compression *int16
	Width       *int32
	Height      *int32
	IsDouble    bool
}

type ComicRating struct {
	UserID    uuid.UUID
	ComicID   uuid.UUID
	Rating    int16
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Device struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Platform   DevicePlatform
	AppVersion *string
	PushToken  *string
	LastSeenAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Favorite struct {
	UserID    uuid.UUID
	ComicID   uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type Folder struct {
	ID         uuid.UUID
	LibraryID  uuid.UUID
	Path       string
	Name       string
	Depth      int32
	ParentPath *string
	Explicit   bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	// Interdit renommage, déplacement, dépôt et suppression. Ne masque rien.
	ReadOnly bool
	// argon2id. Non nul : le dossier est masqué tant qu'il n'est pas déverrouillé.
	AccessCodeHash *string
}

type FolderAccess struct {
	FolderID uuid.UUID
	UserID   uuid.UUID
	CanWrite bool
}

type FolderUnlock struct {
	UserID    uuid.UUID
	FolderID  uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

type Library struct {
	ID               uuid.UUID
	StorageBackendID uuid.UUID
	Name             string
	Kind             LibraryKind
	RootPrefix       string
	ScanOptions      []byte
	ScanCron         *string
	LastScanAt       pgtype.Timestamptz
	LastScanStatus   *string
	ComicCount       int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type LibraryAccess struct {
	LibraryID uuid.UUID
	UserID    uuid.UUID
	CanWrite  bool
}

type ReadingProgress struct {
	UserID     uuid.UUID
	ComicID    uuid.UUID
	Page       int32
	PageCount  int32
	Status     ReadStatus
	ReadCount  int32
	Version    int64
	DeviceID   uuid.NullUUID
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ScanRun struct {
	ID          uuid.UUID
	LibraryID   uuid.UUID
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	Status      string
	ObjectsSeen int32
	Added       int32
	Updated     int32
	Removed     int32
	Errors      int32
	Cursor      *string
	Detail      []byte
}

type Series struct {
	ID           uuid.UUID
	LibraryID    uuid.UUID
	Name         string
	SortName     string
	Description  *string
	Publisher    *string
	Status       *string
	AgeRating    *int16
	YearStarted  *int16
	CoverComicID uuid.NullUUID
	ComicCount   int32
	Metadata     []byte
	LockedFields []string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	DeviceID  uuid.NullUUID
	TokenHash []byte
	ParentID  uuid.NullUUID
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	UserAgent *string
	IP        *netip.Addr
	CreatedAt pgtype.Timestamptz
}

type Setting struct {
	Key       string
	Value     []byte
	UpdatedAt pgtype.Timestamptz
}

type ShareLink struct {
	ID uuid.UUID
	// SHA-256 du jeton. Le jeton en clair n'est montré qu'une fois, à la création.
	TokenHash  []byte
	LibraryID  uuid.UUID
	FolderPath *string
	ComicID    uuid.NullUUID
	Label      string
	CreatedBy  uuid.UUID
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	UseCount   int64
	CreatedAt  pgtype.Timestamptz
}

type StorageBackend struct {
	ID           uuid.UUID
	Name         string
	Kind         StorageKind
	Config       []byte
	SecretsEnc   []byte
	IsDefault    bool
	ReadOnly     bool
	Status       StorageStatus
	StatusDetail *string
	CheckedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        *string
	PasswordHash string
	Role         UserRole
	DisplayName  *string
	AvatarKey    *string
	Restricted   bool
	MaxAgeRating *int16
	Preferences  []byte
	LastLoginAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}
