// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progress.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec

INSERT INTO favorites (user_id, comic_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddFavoriteParams struct {
	UserID  uuid.UUID
	ComicID uuid.UUID
}

// ─── Favoris ─────────────────────────────────────────────────────────────────
func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.ComicID)
	return err
}

const deleteReadingProgress = `-- name: DeleteReadingProgress :exec
DELETE FROM reading_progress WHERE user_id = $1 AND comic_id = $2
`

type DeleteReadingProgressParams struct {
	UserID  uuid.UUID
	ComicID uuid.UUID
}

func (q *Queries) DeleteReadingProgress(ctx context.Context, arg DeleteReadingProgressParams) error {
	_, err := q.db.Exec(ctx, deleteReadingProgress, arg.UserID, arg.ComicID)
	return err
}

const getReadingProgress = `-- name: GetReadingProgress :one
SELECT user_id, comic_id, page, page_count, status, read_count, version, device_id, started_at, finished_at, updated_at FROM reading_progress WHERE user_id = $1 AND comic_id = $2
`

type GetReadingProgressParams struct {
	UserID  uuid.UUID
	ComicID uuid.UUID
}

func (q *Queries) GetReadingProgress(ctx context.Context, arg GetReadingProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRow(ctx, getReadingProgress, arg.UserID, arg.ComicID)
	var i ReadingProgress
	err := row.Scan(
		&i.UserID,
		&i.ComicID,
		&i.Page,
		&i.PageCount,
		&i.Status,
		&i.ReadCount,
		&i.Version,
		&i.DeviceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFavorites = `-- name: ListFavorites :many
SELECT comics.id, comics.library_id, comics.series_id, comics.object_key, comics.file_size, comics.file_etag, comics.content_hash, comics.format, comics.title, comics.number, comics.number_sort, comics.volume, comics.summary, comics.released_at, comics.age_rating, comics.language, comics.page_count, comics.cover_page, comics.state, comics.state_detail, comics.hydrated_at, comics.indexed_at, comics.metadata, comics.locked_fields, comics.created_at, comics.updated_at, comics.deleted_at, comics.search_vector, comics.cover_placeholder, comics.folder_path
FROM favorites
JOIN comics ON comics.id = favorites.comic_id
WHERE favorites.user_id = $1 AND comics.deleted_at IS NULL
ORDER BY favorites.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFavoritesParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type ListFavoritesRow struct {
	Comic Comic
}

func (q *Queries) ListFavorites(ctx context.Context, arg ListFavoritesParams) ([]ListFavoritesRow, error) {
	rows, err := q.db.Query(ctx, listFavorites, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavoritesRow{}
	for rows.Next() {
		var i ListFavoritesRow
		if err := rows.Scan(
			&i.Comic.ID,
			&i.Comic.LibraryID,
			&i.Comic.SeriesID,
			&i.Comic.ObjectKey,
			&i.Comic.FileSize,
			&i.Comic.FileEtag,
			&i.Comic.ContentHash,
			&i.Comic.Format,
			&i.Comic.Title,
			&i.Comic.Number,
			&i.Comic.NumberSort,
			&i.Comic.Volume,
			&i.Comic.Summary,
			&i.Comic.ReleasedAt,
			&i.Comic.AgeRating,
			&i.Comic.Language,
			&i.Comic.PageCount,
			&i.Comic.CoverPage,
			&i.Comic.State,
			&i.Comic.StateDetail,
			&i.Comic.HydratedAt,
			&i.Comic.IndexedAt,
			&i.Comic.Metadata,
			&i.Comic.LockedFields,
			&i.Comic.CreatedAt,
			&i.Comic.UpdatedAt,
			&i.Comic.DeletedAt,
			&i.Comic.SearchVector,
			&i.Comic.CoverPlaceholder,
			&i.Comic.FolderPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInProgress = `-- name: ListInProgress :many
SELECT reading_progress.user_id, reading_progress.comic_id, reading_progress.page, reading_progress.page_count, reading_progress.status, reading_progress.read_count, reading_progress.version, reading_progress.device_id, reading_progress.started_at, reading_progress.finished_at, reading_progress.updated_at, comics.id, comics.library_id, comics.series_id, comics.object_key, comics.file_size, comics.file_etag, comics.content_hash, comics.format, comics.title, comics.number, comics.number_sort, comics.volume, comics.summary, comics.released_at, comics.age_rating, comics.language, comics.page_count, comics.cover_page, comics.state, comics.state_detail, comics.hydrated_at, comics.indexed_at, comics.metadata, comics.locked_fields, comics.created_at, comics.updated_at, comics.deleted_at, comics.search_vector, comics.cover_placeholder, comics.folder_path
FROM reading_progress
JOIN comics ON comics.id = reading_progress.comic_id
WHERE reading_progress.user_id = $1
  AND reading_progress.status = 'in_progress'
  AND comics.deleted_at IS NULL
ORDER BY reading_progress.updated_at DESC
LIMIT $2
`

type ListInProgressParams struct {
	UserID uuid.UUID
	Limit  int32
}

type ListInProgressRow struct {
	ReadingProgress ReadingProgress
	Comic           Comic
}

// « Reprendre la lecture » : les albums commencés mais non terminés.
func (q *Queries) ListInProgress(ctx context.Context, arg ListInProgressParams) ([]ListInProgressRow, error) {
	rows, err := q.db.Query(ctx, listInProgress, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInProgressRow{}
	for rows.Next() {
		var i ListInProgressRow
		if err := rows.Scan(
			&i.ReadingProgress.UserID,
			&i.ReadingProgress.ComicID,
			&i.ReadingProgress.Page,
			&i.ReadingProgress.PageCount,
			&i.ReadingProgress.Status,
			&i.ReadingProgress.ReadCount,
			&i.ReadingProgress.Version,
			&i.ReadingProgress.DeviceID,
			&i.ReadingProgress.StartedAt,
			&i.ReadingProgress.FinishedAt,
			&i.ReadingProgress.UpdatedAt,
			&i.Comic.ID,
			&i.Comic.LibraryID,
			&i.Comic.SeriesID,
			&i.Comic.ObjectKey,
			&i.Comic.FileSize,
			&i.Comic.FileEtag,
			&i.Comic.ContentHash,
			&i.Comic.Format,
			&i.Comic.Title,
			&i.Comic.Number,
			&i.Comic.NumberSort,
			&i.Comic.Volume,
			&i.Comic.Summary,
			&i.Comic.ReleasedAt,
			&i.Comic.AgeRating,
			&i.Comic.Language,
			&i.Comic.PageCount,
			&i.Comic.CoverPage,
			&i.Comic.State,
			&i.Comic.StateDetail,
			&i.Comic.HydratedAt,
			&i.Comic.IndexedAt,
			&i.Comic.Metadata,
			&i.Comic.LockedFields,
			&i.Comic.CreatedAt,
			&i.Comic.UpdatedAt,
			&i.Comic.DeletedAt,
			&i.Comic.SearchVector,
			&i.Comic.CoverPlaceholder,
			&i.Comic.FolderPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingProgressByComics = `-- name: ListReadingProgressByComics :many
SELECT user_id, comic_id, page, page_count, status, read_count, version, device_id, started_at, finished_at, updated_at FROM reading_progress
WHERE user_id = $1 AND comic_id = ANY($2::uuid[])
`

type ListReadingProgressByComicsParams struct {
	UserID  uuid.UUID
	Column2 []uuid.UUID
}

func (q *Queries) ListReadingProgressByComics(ctx context.Context, arg ListReadingProgressByComicsParams) ([]ReadingProgress, error) {
	rows, err := q.db.Query(ctx, listReadingProgressByComics, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadingProgress{}
	for rows.Next() {
		var i ReadingProgress
		if err := rows.Scan(
			&i.UserID,
			&i.ComicID,
			&i.Page,
			&i.PageCount,
			&i.Status,
			&i.ReadCount,
			&i.Version,
			&i.DeviceID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingProgressSince = `-- name: ListReadingProgressSince :many
SELECT user_id, comic_id, page, page_count, status, read_count, version, device_id, started_at, finished_at, updated_at FROM reading_progress
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at
LIMIT $3
`

type ListReadingProgressSinceParams struct {
	UserID    uuid.UUID
	UpdatedAt pgtype.Timestamptz
	Limit     int32
}

// Synchronisation delta : tout ce qui a changé depuis le curseur du client.
func (q *Queries) ListReadingProgressSince(ctx context.Context, arg ListReadingProgressSinceParams) ([]ReadingProgress, error) {
	rows, err := q.db.Query(ctx, listReadingProgressSince, arg.UserID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadingProgress{}
	for rows.Next() {
		var i ReadingProgress
		if err := rows.Scan(
			&i.UserID,
			&i.ComicID,
			&i.Page,
			&i.PageCount,
			&i.Status,
			&i.ReadCount,
			&i.Version,
			&i.DeviceID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites WHERE user_id = $1 AND comic_id = $2
`

type RemoveFavoriteParams struct {
	UserID  uuid.UUID
	ComicID uuid.UUID
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.ComicID)
	return err
}

const upsertReadingProgress = `-- name: UpsertReadingProgress :one

INSERT INTO reading_progress (
    user_id, comic_id, page, page_count, status, device_id,
    read_count, started_at, finished_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    -- Un album marqué lu dès la première écriture compte pour une lecture.
    -- Sans cela, seuls les albums passés par « en cours » seraient comptés, et
    -- un import de progression depuis un autre lecteur donnerait zéro partout.
    CASE WHEN $5::read_status = 'read' THEN 1 ELSE 0 END,
    CASE WHEN $3 > 0 THEN now() ELSE NULL END,
    CASE WHEN $5::read_status = 'read' THEN now() ELSE NULL END,
    now()
)
ON CONFLICT (user_id, comic_id) DO UPDATE
SET page = CASE
        WHEN EXCLUDED.status = 'unread' THEN EXCLUDED.page
        WHEN EXCLUDED.page > reading_progress.page THEN EXCLUDED.page
        ELSE reading_progress.page
    END,
    page_count = EXCLUDED.page_count,
    status = CASE
        WHEN EXCLUDED.status = 'unread' THEN 'unread'::read_status
        WHEN EXCLUDED.status = 'read' OR reading_progress.status = 'read' THEN 'read'::read_status
        ELSE 'in_progress'::read_status
    END,
    read_count = reading_progress.read_count
        + CASE WHEN EXCLUDED.status = 'read' AND reading_progress.status <> 'read' THEN 1 ELSE 0 END,
    finished_at = CASE
        WHEN EXCLUDED.status = 'read' AND reading_progress.finished_at IS NULL THEN now()
        WHEN EXCLUDED.status = 'unread' THEN NULL
        ELSE reading_progress.finished_at
    END,
    started_at = coalesce(reading_progress.started_at, EXCLUDED.started_at),
    version = reading_progress.version + 1,
    device_id = EXCLUDED.device_id,
    updated_at = now()
RETURNING user_id, comic_id, page, page_count, status, read_count, version, device_id, started_at, finished_at, updated_at
`

type UpsertReadingProgressParams struct {
	UserID    uuid.UUID
	ComicID   uuid.UUID
	Page      int32
	PageCount int32
	Status    ReadStatus
	DeviceID  uuid.NullUUID
}

// Progression de lecture et synchronisation.
// ★ La requête qui porte la règle de résolution de conflit.
//
// Deux appareils peuvent écrire la même progression hors ligne, puis se
// synchroniser. La règle retenue : **la page la plus avancée gagne**, sauf
// remise à zéro explicite (status = 'unread').
//
// C'est le comportement qu'attend un lecteur : on ne perd jamais sa
// progression, et lire sur tablette puis reprendre sur téléphone reprend au bon
// endroit. Un « dernière écriture gagne » ferait régresser la position dès que
// les horloges des appareils divergent un peu.
func (q *Queries) UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRow(ctx, upsertReadingProgress,
		arg.UserID,
		arg.ComicID,
		arg.Page,
		arg.PageCount,
		arg.Status,
		arg.DeviceID,
	)
	var i ReadingProgress
	err := row.Scan(
		&i.UserID,
		&i.ComicID,
		&i.Page,
		&i.PageCount,
		&i.Status,
		&i.ReadCount,
		&i.Version,
		&i.DeviceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}
