// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	DeleteSetting(ctx context.Context, key string) error
	// Paramètres d'instance.
	//
	// Première requête du projet : elle valide la chaîne sqlc de bout en bout.
	// Le schéma métier arrive avec M1.
	GetSetting(ctx context.Context, key string) (Setting, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error)
}

var _ Querier = (*Queries)(nil)
