// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// ─── Favoris ─────────────────────────────────────────────────────────────────
	AddFavorite(ctx context.Context, arg AddFavoriteParams) error
	// Applique les métadonnées issues de ComicInfo.xml ou du nom de fichier.
	// Les champs présents dans locked_fields sont préservés : une saisie manuelle
	// ne doit jamais être écrasée par un rescan.
	ApplyComicMetadata(ctx context.Context, arg ApplyComicMetadataParams) error
	CanAccessLibrary(ctx context.Context, arg CanAccessLibraryParams) (*bool, error)
	// Un seul backend par défaut : on retire le drapeau aux autres avant de le
	// poser, l'index unique partiel refuserait sinon la mise à jour.
	ClearDefaultStorageBackend(ctx context.Context, id uuid.UUID) error
	CountComicPages(ctx context.Context, comicID uuid.UUID) (int64, error)
	CountComicsByLibrary(ctx context.Context, libraryID uuid.UUID) (int64, error)
	// Sert à l'assistant de première installation : tant qu'il n'y a personne,
	// l'inscription du premier administrateur est ouverte.
	CountUsers(ctx context.Context) (int64, error)
	CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error)
	// ─── Sessions ────────────────────────────────────────────────────────────────
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStorageBackend(ctx context.Context, arg CreateStorageBackendParams) (StorageBackend, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCacheEntry(ctx context.Context, key string) error
	DeleteComic(ctx context.Context, id uuid.UUID) error
	// ─── Pages ───────────────────────────────────────────────────────────────────
	DeleteComicPages(ctx context.Context, comicID uuid.UUID) error
	DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteLibrary(ctx context.Context, id uuid.UUID) error
	DeleteReadingProgress(ctx context.Context, arg DeleteReadingProgressParams) error
	DeleteSetting(ctx context.Context, key string) error
	DeleteStorageBackend(ctx context.Context, id uuid.UUID) error
	FinishScanRun(ctx context.Context, arg FinishScanRunParams) error
	GetComic(ctx context.Context, id uuid.UUID) (Comic, error)
	GetComicByObjectKey(ctx context.Context, arg GetComicByObjectKeyParams) (Comic, error)
	GetComicDetail(ctx context.Context, id uuid.UUID) (GetComicDetailRow, error)
	// ★ La requête du chemin chaud : servir une page.
	// Un seul aller-retour en base, puis un seul ReadRange sur le backend.
	GetComicPage(ctx context.Context, arg GetComicPageParams) (ComicPage, error)
	GetDefaultStorageBackend(ctx context.Context) (StorageBackend, error)
	GetDevice(ctx context.Context, id uuid.UUID) (Device, error)
	GetLibrary(ctx context.Context, id uuid.UUID) (Library, error)
	GetLibraryByName(ctx context.Context, name string) (Library, error)
	GetReadingProgress(ctx context.Context, arg GetReadingProgressParams) (ReadingProgress, error)
	GetScanRun(ctx context.Context, id uuid.UUID) (ScanRun, error)
	GetSeries(ctx context.Context, id uuid.UUID) (Series, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error)
	// Paramètres d'instance.
	//
	// Première requête du projet : elle valide la chaîne sqlc de bout en bout.
	// Le schéma métier arrive avec M1.
	GetSetting(ctx context.Context, key string) (Setting, error)
	GetStorageBackend(ctx context.Context, id uuid.UUID) (StorageBackend, error)
	GetStorageBackendByName(ctx context.Context, name string) (StorageBackend, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GrantLibraryAccess(ctx context.Context, arg GrantLibraryAccessParams) error
	InsertComicPage(ctx context.Context, arg InsertComicPageParams) error
	ListCacheEntriesForEviction(ctx context.Context, limit int32) ([]ListCacheEntriesForEvictionRow, error)
	ListComicPages(ctx context.Context, comicID uuid.UUID) ([]ComicPage, error)
	ListComicsByLibrary(ctx context.Context, arg ListComicsByLibraryParams) ([]Comic, error)
	ListComicsBySeries(ctx context.Context, seriesID uuid.NullUUID) ([]Comic, error)
	// Requêtes de consultation du catalogue.
	//
	// Pagination par curseur plutôt que par OFFSET : sur une bibliothèque de
	// plusieurs milliers de titres, OFFSET force PostgreSQL à parcourir puis jeter
	// toutes les lignes précédentes, et une insertion pendant la pagination décale
	// silencieusement les résultats. Le curseur est stable et à coût constant.
	// Liste paginée, filtrable et triable.
	//
	// Le tri est porté par la requête plutôt que par une concaténation côté Go :
	// une clause ORDER BY construite en chaîne serait une porte d'injection, et le
	// plan d'exécution ne serait plus mis en cache. Les trois ordres possibles sont
	// donc écrits en dur, sélectionnés par un paramètre.
	//
	// Le curseur suit l'ordre choisi : (created_at, id) pour le tri par ajout,
	// (title, id) pour le tri alphabétique. Un seul curseur composite ne
	// conviendrait pas aux deux.
	ListComicsPage(ctx context.Context, arg ListComicsPageParams) ([]Comic, error)
	ListDevicesByUser(ctx context.Context, userID uuid.UUID) ([]Device, error)
	ListFavorites(ctx context.Context, arg ListFavoritesParams) ([]ListFavoritesRow, error)
	// « Reprendre la lecture » : les albums commencés mais non terminés.
	ListInProgress(ctx context.Context, arg ListInProgressParams) ([]ListInProgressRow, error)
	ListLibraries(ctx context.Context) ([]Library, error)
	ListLibrariesWithBackend(ctx context.Context) ([]ListLibrariesWithBackendRow, error)
	ListLibraryAccess(ctx context.Context, libraryID uuid.UUID) ([]LibraryAccess, error)
	// Étagère « Suite de la série » : le premier album non lu de chaque série déjà
	// entamée. C'est la suggestion la plus utile d'une page d'accueil de lecteur.
	ListNextInSeries(ctx context.Context, arg ListNextInSeriesParams) ([]Comic, error)
	ListReadingProgressByComics(ctx context.Context, arg ListReadingProgressByComicsParams) ([]ReadingProgress, error)
	// Synchronisation delta : tout ce qui a changé depuis le curseur du client.
	ListReadingProgressSince(ctx context.Context, arg ListReadingProgressSinceParams) ([]ReadingProgress, error)
	// Étagère d'accueil : les derniers albums ajoutés.
	ListRecentComics(ctx context.Context, arg ListRecentComicsParams) ([]Comic, error)
	ListScanRuns(ctx context.Context, arg ListScanRunsParams) ([]ScanRun, error)
	ListSeriesByLibrary(ctx context.Context, libraryID uuid.UUID) ([]Series, error)
	ListSeriesPage(ctx context.Context, arg ListSeriesPageParams) ([]Series, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListStorageBackends(ctx context.Context) ([]StorageBackend, error)
	ListUsers(ctx context.Context) ([]User, error)
	// ─── Accès aux bibliothèques ─────────────────────────────────────────────────
	// Bibliothèques visibles par un utilisateur.
	//
	// Règle : une bibliothèque sans aucune restriction est visible de tous ; dès
	// qu'une restriction existe, seuls les utilisateurs listés y ont accès. Les
	// administrateurs voient tout.
	ListVisibleLibraries(ctx context.Context, arg ListVisibleLibrariesParams) ([]Library, error)
	// Marque comme supprimés les objets absents du dernier scan.
	// On ne supprime pas la ligne : un backend momentanément injoignable ne doit
	// pas détruire la progression de lecture des utilisateurs.
	MarkMissingComicsDeleted(ctx context.Context, arg MarkMissingComicsDeletedParams) (int64, error)
	// ─── Cache dérivé ────────────────────────────────────────────────────────────
	RecordCacheEntry(ctx context.Context, arg RecordCacheEntryParams) error
	RefreshSeriesCounts(ctx context.Context, libraryID uuid.UUID) error
	RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) (int64, error)
	RevokeLibraryAccess(ctx context.Context, arg RevokeLibraryAccessParams) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	// Détection de réutilisation : si un jeton déjà tourné est présenté, c'est
	// qu'il a été volé. On révoque alors toute la chaîne de rotation, pas
	// seulement le jeton présenté.
	RevokeSessionChain(ctx context.Context, id uuid.UUID) (int64, error)
	// Recherche plein texte, avec repli sur la similarité trigramme.
	//
	// Les deux sont combinés parce qu'ils échouent différemment :
	// websearch_to_tsquery gère les expressions et les mots multiples mais rate
	// les fautes de frappe ; la similarité trigramme rattrape « asterics » →
	// « Astérix » mais ne comprend pas les requêtes à plusieurs mots.
	//
	// word_similarity plutôt que similarity : cette dernière compare la requête au
	// titre ENTIER, si bien qu'un titre long fait chuter le score sous le seuil.
	// Mesuré sur « asterics » contre « Astérix le Gaulois » : similarity = 0,27
	// (rejeté), word_similarity = 0,67 (accepté). word_similarity cherche la
	// meilleure sous-séquence de mots, ce qui est le comportement attendu quand on
	// tape un seul mot d'un titre.
	//
	// Tout est désaccentué de part et d'autre : personne ne saisit les accents
	// dans un champ de recherche, et c'est rédhibitoire sur de la BD franco-belge.
	SearchComics(ctx context.Context, arg SearchComicsParams) ([]SearchComicsRow, error)
	SearchSeries(ctx context.Context, arg SearchSeriesParams) ([]SearchSeriesRow, error)
	SetComicIndexed(ctx context.Context, arg SetComicIndexedParams) error
	SetComicPlaceholder(ctx context.Context, arg SetComicPlaceholderParams) error
	SetComicState(ctx context.Context, arg SetComicStateParams) error
	SetDefaultStorageBackend(ctx context.Context, id uuid.UUID) error
	SetLibraryScanResult(ctx context.Context, arg SetLibraryScanResultParams) error
	SetStorageBackendStatus(ctx context.Context, arg SetStorageBackendStatusParams) error
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	SetUserRole(ctx context.Context, arg SetUserRoleParams) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	// ─── Scans ───────────────────────────────────────────────────────────────────
	StartScanRun(ctx context.Context, arg StartScanRunParams) (ScanRun, error)
	TotalCacheSize(ctx context.Context) (int64, error)
	TouchCacheEntry(ctx context.Context, key string) error
	TouchDevice(ctx context.Context, id uuid.UUID) error
	TouchUserLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	// Ingestion idempotente : la clé naturelle (library_id, object_key) permet de
	// rejouer un scan sans créer de doublon ni perdre les champs verrouillés.
	UpsertComic(ctx context.Context, arg UpsertComicParams) (UpsertComicRow, error)
	// ─── Appareils ───────────────────────────────────────────────────────────────
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error)
	// Progression de lecture et synchronisation.
	// ★ La requête qui porte la règle de résolution de conflit.
	//
	// Deux appareils peuvent écrire la même progression hors ligne, puis se
	// synchroniser. La règle retenue : **la page la plus avancée gagne**, sauf
	// remise à zéro explicite (status = 'unread').
	//
	// C'est le comportement qu'attend un lecteur : on ne perd jamais sa
	// progression, et lire sur tablette puis reprendre sur téléphone reprend au bon
	// endroit. Un « dernière écriture gagne » ferait régresser la position dès que
	// les horloges des appareils divergent un peu.
	UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) (ReadingProgress, error)
	// ─── Séries ──────────────────────────────────────────────────────────────────
	UpsertSeries(ctx context.Context, arg UpsertSeriesParams) (Series, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error)
}

var _ Querier = (*Queries)(nil)
