// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage_backends.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const clearDefaultStorageBackend = `-- name: ClearDefaultStorageBackend :exec
UPDATE storage_backends SET is_default = false WHERE is_default AND id <> $1
`

// Un seul backend par défaut : on retire le drapeau aux autres avant de le
// poser, l'index unique partiel refuserait sinon la mise à jour.
func (q *Queries) ClearDefaultStorageBackend(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultStorageBackend, id)
	return err
}

const createStorageBackend = `-- name: CreateStorageBackend :one
INSERT INTO storage_backends (id, name, kind, config, secrets_enc, is_default, read_only)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, kind, config, secrets_enc, is_default, read_only, status, status_detail, checked_at, created_at, updated_at
`

type CreateStorageBackendParams struct {
	ID         uuid.UUID
	Name       string
	Kind       StorageKind
	Config     []byte
	SecretsEnc []byte
	IsDefault  bool
	ReadOnly   bool
}

func (q *Queries) CreateStorageBackend(ctx context.Context, arg CreateStorageBackendParams) (StorageBackend, error) {
	row := q.db.QueryRow(ctx, createStorageBackend,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Config,
		arg.SecretsEnc,
		arg.IsDefault,
		arg.ReadOnly,
	)
	var i StorageBackend
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.SecretsEnc,
		&i.IsDefault,
		&i.ReadOnly,
		&i.Status,
		&i.StatusDetail,
		&i.CheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStorageBackend = `-- name: DeleteStorageBackend :exec
DELETE FROM storage_backends WHERE id = $1
`

func (q *Queries) DeleteStorageBackend(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStorageBackend, id)
	return err
}

const getDefaultStorageBackend = `-- name: GetDefaultStorageBackend :one
SELECT id, name, kind, config, secrets_enc, is_default, read_only, status, status_detail, checked_at, created_at, updated_at FROM storage_backends WHERE is_default LIMIT 1
`

func (q *Queries) GetDefaultStorageBackend(ctx context.Context) (StorageBackend, error) {
	row := q.db.QueryRow(ctx, getDefaultStorageBackend)
	var i StorageBackend
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.SecretsEnc,
		&i.IsDefault,
		&i.ReadOnly,
		&i.Status,
		&i.StatusDetail,
		&i.CheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStorageBackend = `-- name: GetStorageBackend :one
SELECT id, name, kind, config, secrets_enc, is_default, read_only, status, status_detail, checked_at, created_at, updated_at FROM storage_backends WHERE id = $1
`

func (q *Queries) GetStorageBackend(ctx context.Context, id uuid.UUID) (StorageBackend, error) {
	row := q.db.QueryRow(ctx, getStorageBackend, id)
	var i StorageBackend
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.SecretsEnc,
		&i.IsDefault,
		&i.ReadOnly,
		&i.Status,
		&i.StatusDetail,
		&i.CheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStorageBackendByName = `-- name: GetStorageBackendByName :one
SELECT id, name, kind, config, secrets_enc, is_default, read_only, status, status_detail, checked_at, created_at, updated_at FROM storage_backends WHERE name = $1
`

func (q *Queries) GetStorageBackendByName(ctx context.Context, name string) (StorageBackend, error) {
	row := q.db.QueryRow(ctx, getStorageBackendByName, name)
	var i StorageBackend
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.SecretsEnc,
		&i.IsDefault,
		&i.ReadOnly,
		&i.Status,
		&i.StatusDetail,
		&i.CheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStorageBackends = `-- name: ListStorageBackends :many
SELECT id, name, kind, config, secrets_enc, is_default, read_only, status, status_detail, checked_at, created_at, updated_at FROM storage_backends ORDER BY is_default DESC, name
`

func (q *Queries) ListStorageBackends(ctx context.Context) ([]StorageBackend, error) {
	rows, err := q.db.Query(ctx, listStorageBackends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageBackend{}
	for rows.Next() {
		var i StorageBackend
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Config,
			&i.SecretsEnc,
			&i.IsDefault,
			&i.ReadOnly,
			&i.Status,
			&i.StatusDetail,
			&i.CheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultStorageBackend = `-- name: SetDefaultStorageBackend :exec
UPDATE storage_backends SET is_default = true WHERE id = $1
`

func (q *Queries) SetDefaultStorageBackend(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setDefaultStorageBackend, id)
	return err
}

const setStorageBackendStatus = `-- name: SetStorageBackendStatus :exec
UPDATE storage_backends
SET status = $2, status_detail = $3, checked_at = now()
WHERE id = $1
`

type SetStorageBackendStatusParams struct {
	ID           uuid.UUID
	Status       StorageStatus
	StatusDetail *string
}

func (q *Queries) SetStorageBackendStatus(ctx context.Context, arg SetStorageBackendStatusParams) error {
	_, err := q.db.Exec(ctx, setStorageBackendStatus, arg.ID, arg.Status, arg.StatusDetail)
	return err
}

const updateStorageBackend = `-- name: UpdateStorageBackend :one
UPDATE storage_backends
SET name      = coalesce($2, name),
    config    = coalesce($3, config),
    -- Les secrets ne sont remplacés que s'ils sont fournis : réenregistrer un
    -- backend sans les retaper ne doit pas les effacer.
    secrets_enc = coalesce($4, secrets_enc),
    read_only = coalesce($5, read_only)
WHERE id = $1
RETURNING id, name, kind, config, secrets_enc, is_default, read_only, status, status_detail, checked_at, created_at, updated_at
`

type UpdateStorageBackendParams struct {
	ID         uuid.UUID
	Name       *string
	Config     []byte
	SecretsEnc []byte
	ReadOnly   *bool
}

func (q *Queries) UpdateStorageBackend(ctx context.Context, arg UpdateStorageBackendParams) (StorageBackend, error) {
	row := q.db.QueryRow(ctx, updateStorageBackend,
		arg.ID,
		arg.Name,
		arg.Config,
		arg.SecretsEnc,
		arg.ReadOnly,
	)
	var i StorageBackend
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.SecretsEnc,
		&i.IsDefault,
		&i.ReadOnly,
		&i.Status,
		&i.StatusDetail,
		&i.CheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
