// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tools.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bulkMarkRead = `-- name: BulkMarkRead :execrows

INSERT INTO reading_progress (user_id, comic_id, page, page_count, status, read_count, started_at, finished_at)
SELECT $1, c.id, greatest(c.page_count - 1, 0), c.page_count, 'read', 1, now(), now()
FROM comics c
WHERE c.id = ANY($2::uuid[])
ON CONFLICT (user_id, comic_id) DO UPDATE
SET page = excluded.page,
    page_count = excluded.page_count,
    status = 'read',
    read_count = reading_progress.read_count
        + CASE WHEN reading_progress.status <> 'read' THEN 1 ELSE 0 END,
    finished_at = coalesce(reading_progress.finished_at, now()),
    version = reading_progress.version + 1,
    updated_at = now()
`

type BulkMarkReadParams struct {
	UserID  uuid.UUID
	Column2 []uuid.UUID
}

// ─── Actions en lot ──────────────────────────────────────────────────────────
// Marque un lot d'albums comme lus.
//
// page est fixée à la dernière page de chaque album : marquer lu doit donner le
// même état que lire jusqu'au bout, sans quoi « reprendre la lecture »
// proposerait un album déjà déclaré terminé.
func (q *Queries) BulkMarkRead(ctx context.Context, arg BulkMarkReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkMarkRead, arg.UserID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkMarkUnread = `-- name: BulkMarkUnread :execrows
DELETE FROM reading_progress
WHERE user_id = $1 AND comic_id = ANY($2::uuid[])
`

type BulkMarkUnreadParams struct {
	UserID  uuid.UUID
	Column2 []uuid.UUID
}

func (q *Queries) BulkMarkUnread(ctx context.Context, arg BulkMarkUnreadParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkMarkUnread, arg.UserID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkSetFavorite = `-- name: BulkSetFavorite :execrows
INSERT INTO favorites (user_id, comic_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type BulkSetFavoriteParams struct {
	UserID  uuid.UUID
	Column2 []uuid.UUID
}

func (q *Queries) BulkSetFavorite(ctx context.Context, arg BulkSetFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkSetFavorite, arg.UserID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkUnsetFavorite = `-- name: BulkUnsetFavorite :execrows
DELETE FROM favorites WHERE user_id = $1 AND comic_id = ANY($2::uuid[])
`

type BulkUnsetFavoriteParams struct {
	UserID  uuid.UUID
	Column2 []uuid.UUID
}

func (q *Queries) BulkUnsetFavorite(ctx context.Context, arg BulkUnsetFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkUnsetFavorite, arg.UserID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const canWriteFolder = `-- name: CanWriteFolder :one
SELECT EXISTS (
    SELECT 1 FROM folders f
    JOIN folder_access a ON a.folder_id = f.id
    WHERE f.library_id = $1
      AND a.user_id = $2
      AND a.can_write = true
      AND ($3::text = f.path OR $3::text LIKE f.path || '/%')
) AS allowed
`

type CanWriteFolderParams struct {
	LibraryID uuid.UUID
	UserID    uuid.UUID
	Path      string
}

// Le dossier ou l'un de ses ancêtres autorise-t-il ce compte à écrire ?
func (q *Queries) CanWriteFolder(ctx context.Context, arg CanWriteFolderParams) (bool, error) {
	row := q.db.QueryRow(ctx, canWriteFolder, arg.LibraryID, arg.UserID, arg.Path)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const clearRating = `-- name: ClearRating :exec
DELETE FROM comic_ratings WHERE user_id = $1 AND comic_id = $2
`

type ClearRatingParams struct {
	UserID  uuid.UUID
	ComicID uuid.UUID
}

func (q *Queries) ClearRating(ctx context.Context, arg ClearRatingParams) error {
	_, err := q.db.Exec(ctx, clearRating, arg.UserID, arg.ComicID)
	return err
}

const comicInSharedFolder = `-- name: ComicInSharedFolder :one
SELECT EXISTS (
    SELECT 1 FROM comics c
    WHERE c.id = $1
      AND c.library_id = $2
      AND c.deleted_at IS NULL
      AND c.excluded_at IS NULL
      AND ($3::text = '' OR c.folder_path = $3::text OR c.folder_path LIKE $3::text || '/%')
) AS included
`

type ComicInSharedFolderParams struct {
	ID        uuid.UUID
	LibraryID uuid.UUID
	Path      string
}

// Un album donné entre-t-il dans la portée d'un lien de dossier ?
func (q *Queries) ComicInSharedFolder(ctx context.Context, arg ComicInSharedFolderParams) (bool, error) {
	row := q.db.QueryRow(ctx, comicInSharedFolder, arg.ID, arg.LibraryID, arg.Path)
	var included bool
	err := row.Scan(&included)
	return included, err
}

const countComicsByExactFolder = `-- name: CountComicsByExactFolder :many
SELECT c.library_id, c.folder_path, count(*)::int AS comic_count
FROM comics c
WHERE c.library_id = ANY($1::uuid[])
  AND c.deleted_at IS NULL
  AND c.excluded_at IS NULL
GROUP BY c.library_id, c.folder_path
`

type CountComicsByExactFolderRow struct {
	LibraryID  uuid.UUID
	FolderPath string
	ComicCount int32
}

// Comptes d'albums par dossier exact, sans les descendants.
// Le cumul se fait ensuite en une passe côté service.
func (q *Queries) CountComicsByExactFolder(ctx context.Context, libraryIds []uuid.UUID) ([]CountComicsByExactFolderRow, error) {
	rows, err := q.db.Query(ctx, countComicsByExactFolder, libraryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountComicsByExactFolderRow{}
	for rows.Next() {
		var i CountComicsByExactFolderRow
		if err := rows.Scan(&i.LibraryID, &i.FolderPath, &i.ComicCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createShareLink = `-- name: CreateShareLink :one

INSERT INTO share_links (
    id, token_hash, library_id, folder_path, comic_id, label, created_by, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, token_hash, library_id, folder_path, comic_id, label, created_by, expires_at, revoked_at, last_used_at, use_count, created_at
`

type CreateShareLinkParams struct {
	ID         uuid.UUID
	TokenHash  []byte
	LibraryID  uuid.UUID
	FolderPath *string
	ComicID    uuid.NullUUID
	Label      string
	CreatedBy  uuid.UUID
	ExpiresAt  pgtype.Timestamptz
}

// ─── Liens publics ───────────────────────────────────────────────────────────
func (q *Queries) CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error) {
	row := q.db.QueryRow(ctx, createShareLink,
		arg.ID,
		arg.TokenHash,
		arg.LibraryID,
		arg.FolderPath,
		arg.ComicID,
		arg.Label,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.LibraryID,
		&i.FolderPath,
		&i.ComicID,
		&i.Label,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.UseCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFolderTree = `-- name: DeleteFolderTree :execrows
DELETE FROM folders
WHERE library_id = $1
  AND (path = $2::text OR path LIKE $2::text || '/%')
`

type DeleteFolderTreeParams struct {
	LibraryID uuid.UUID
	Path      string
}

func (q *Queries) DeleteFolderTree(ctx context.Context, arg DeleteFolderTreeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFolderTree, arg.LibraryID, arg.Path)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const editComic = `-- name: EditComic :one

UPDATE comics
SET title       = coalesce($1, title),
    number      = coalesce($2, number),
    summary     = coalesce($3, summary),
    language    = coalesce($4, language),
    locked_fields = (
        SELECT array_agg(DISTINCT f) FROM unnest(
            locked_fields || $5::text[]
        ) AS f
    )
WHERE id = $6
RETURNING id, library_id, series_id, object_key, file_size, file_etag, content_hash, format, title, number, number_sort, volume, summary, released_at, age_rating, language, page_count, cover_page, state, state_detail, hydrated_at, indexed_at, metadata, locked_fields, created_at, updated_at, deleted_at, search_vector, cover_placeholder, folder_path, excluded_at
`

type EditComicParams struct {
	Title       *string
	Number      *string
	Summary     *string
	Language    *string
	NewlyLocked []string
	ID          uuid.UUID
}

// ─── Édition manuelle ────────────────────────────────────────────────────────
// Édition d'un album par l'utilisateur.
//
// Chaque champ renseigné entre dans locked_fields : une réindexation ne doit
// jamais écraser une saisie manuelle. C'est la contrepartie de l'automatisme —
// sans elle, corriger un titre serait inutile.
func (q *Queries) EditComic(ctx context.Context, arg EditComicParams) (Comic, error) {
	row := q.db.QueryRow(ctx, editComic,
		arg.Title,
		arg.Number,
		arg.Summary,
		arg.Language,
		arg.NewlyLocked,
		arg.ID,
	)
	var i Comic
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.SeriesID,
		&i.ObjectKey,
		&i.FileSize,
		&i.FileEtag,
		&i.ContentHash,
		&i.Format,
		&i.Title,
		&i.Number,
		&i.NumberSort,
		&i.Volume,
		&i.Summary,
		&i.ReleasedAt,
		&i.AgeRating,
		&i.Language,
		&i.PageCount,
		&i.CoverPage,
		&i.State,
		&i.StateDetail,
		&i.HydratedAt,
		&i.IndexedAt,
		&i.Metadata,
		&i.LockedFields,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
		&i.CoverPlaceholder,
		&i.FolderPath,
		&i.ExcludedAt,
	)
	return i, err
}

const excludeComic = `-- name: ExcludeComic :exec

UPDATE comics
SET deleted_at  = coalesce(deleted_at, now()),
    excluded_at = now()
WHERE id = $1
`

// ─── Suppression et déplacement ──────────────────────────────────────────────
// Retire l'album du catalogue sans effacer sa ligne.
//
// La progression de lecture, les favoris et les notes y sont rattachés : les
// détruire priverait d'historique quelqu'un qui remettrait le fichier en place.
func (q *Queries) ExcludeComic(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, excludeComic, id)
	return err
}

const getFolder = `-- name: GetFolder :one
SELECT id, library_id, path, name, depth, parent_path, explicit, created_at, updated_at, read_only, access_code_hash FROM folders WHERE library_id = $1 AND path = $2
`

type GetFolderParams struct {
	LibraryID uuid.UUID
	Path      string
}

func (q *Queries) GetFolder(ctx context.Context, arg GetFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolder, arg.LibraryID, arg.Path)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Path,
		&i.Name,
		&i.Depth,
		&i.ParentPath,
		&i.Explicit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadOnly,
		&i.AccessCodeHash,
	)
	return i, err
}

const getFolderAccessCode = `-- name: GetFolderAccessCode :one
SELECT id, access_code_hash FROM folders WHERE library_id = $1 AND path = $2
`

type GetFolderAccessCodeParams struct {
	LibraryID uuid.UUID
	Path      string
}

type GetFolderAccessCodeRow struct {
	ID             uuid.UUID
	AccessCodeHash *string
}

func (q *Queries) GetFolderAccessCode(ctx context.Context, arg GetFolderAccessCodeParams) (GetFolderAccessCodeRow, error) {
	row := q.db.QueryRow(ctx, getFolderAccessCode, arg.LibraryID, arg.Path)
	var i GetFolderAccessCodeRow
	err := row.Scan(&i.ID, &i.AccessCodeHash)
	return i, err
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, library_id, path, name, depth, parent_path, explicit, created_at, updated_at, read_only, access_code_hash FROM folders WHERE id = $1
`

func (q *Queries) GetFolderByID(ctx context.Context, id uuid.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Path,
		&i.Name,
		&i.Depth,
		&i.ParentPath,
		&i.Explicit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadOnly,
		&i.AccessCodeHash,
	)
	return i, err
}

const getShareLinkByHash = `-- name: GetShareLinkByHash :one
SELECT id, token_hash, library_id, folder_path, comic_id, label, created_by, expires_at, revoked_at, last_used_at, use_count, created_at FROM share_links
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

// Résolution d'un lien à partir du hachage de son jeton.
//
// Les liens révoqués ou expirés ne sortent pas : le filtre est dans la requête
// plutôt qu'après, pour qu'aucun appelant ne puisse l'oublier.
func (q *Queries) GetShareLinkByHash(ctx context.Context, tokenHash []byte) (ShareLink, error) {
	row := q.db.QueryRow(ctx, getShareLinkByHash, tokenHash)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.LibraryID,
		&i.FolderPath,
		&i.ComicID,
		&i.Label,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.UseCount,
		&i.CreatedAt,
	)
	return i, err
}

const grantFolderAccess = `-- name: GrantFolderAccess :exec

INSERT INTO folder_access (folder_id, user_id, can_write)
VALUES ($1, $2, $3)
ON CONFLICT (folder_id, user_id) DO UPDATE SET can_write = EXCLUDED.can_write
`

type GrantFolderAccessParams struct {
	FolderID uuid.UUID
	UserID   uuid.UUID
	CanWrite bool
}

// ─── Partage entre comptes ───────────────────────────────────────────────────
func (q *Queries) GrantFolderAccess(ctx context.Context, arg GrantFolderAccessParams) error {
	_, err := q.db.Exec(ctx, grantFolderAccess, arg.FolderID, arg.UserID, arg.CanWrite)
	return err
}

const isFolderTreeReadOnly = `-- name: IsFolderTreeReadOnly :one
SELECT EXISTS (
    SELECT 1 FROM folders
    WHERE library_id = $1
      AND read_only = true
      AND ($2::text = path OR $2::text LIKE path || '/%')
) AS locked
`

type IsFolderTreeReadOnlyParams struct {
	LibraryID uuid.UUID
	Path      string
}

// Le dossier lui-même ou l'un de ses ancêtres est-il en lecture seule ?
//
// La protection est héritée : verrouiller « BD » protège tout ce qu'il contient,
// ce qu'on attend de ce geste. La vérifier ancêtre par ancêtre côté service
// coûterait une requête par niveau.
func (q *Queries) IsFolderTreeReadOnly(ctx context.Context, arg IsFolderTreeReadOnlyParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFolderTreeReadOnly, arg.LibraryID, arg.Path)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}

const listComicsInFolderTree = `-- name: ListComicsInFolderTree :many
SELECT id, object_key FROM comics
WHERE library_id = $1
  AND deleted_at IS NULL
  AND (folder_path = $2::text OR folder_path LIKE $2::text || '/%')
ORDER BY object_key
`

type ListComicsInFolderTreeParams struct {
	LibraryID uuid.UUID
	Path      string
}

type ListComicsInFolderTreeRow struct {
	ID        uuid.UUID
	ObjectKey string
}

func (q *Queries) ListComicsInFolderTree(ctx context.Context, arg ListComicsInFolderTreeParams) ([]ListComicsInFolderTreeRow, error) {
	rows, err := q.db.Query(ctx, listComicsInFolderTree, arg.LibraryID, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComicsInFolderTreeRow{}
	for rows.Next() {
		var i ListComicsInFolderTreeRow
		if err := rows.Scan(&i.ID, &i.ObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExcludedComics = `-- name: ListExcludedComics :many
SELECT id, library_id, series_id, object_key, file_size, file_etag, content_hash, format, title, number, number_sort, volume, summary, released_at, age_rating, language, page_count, cover_page, state, state_detail, hydrated_at, indexed_at, metadata, locked_fields, created_at, updated_at, deleted_at, search_vector, cover_placeholder, folder_path, excluded_at FROM comics
WHERE library_id = $1 AND excluded_at IS NOT NULL
ORDER BY title
`

func (q *Queries) ListExcludedComics(ctx context.Context, libraryID uuid.UUID) ([]Comic, error) {
	rows, err := q.db.Query(ctx, listExcludedComics, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comic{}
	for rows.Next() {
		var i Comic
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.SeriesID,
			&i.ObjectKey,
			&i.FileSize,
			&i.FileEtag,
			&i.ContentHash,
			&i.Format,
			&i.Title,
			&i.Number,
			&i.NumberSort,
			&i.Volume,
			&i.Summary,
			&i.ReleasedAt,
			&i.AgeRating,
			&i.Language,
			&i.PageCount,
			&i.CoverPage,
			&i.State,
			&i.StateDetail,
			&i.HydratedAt,
			&i.IndexedAt,
			&i.Metadata,
			&i.LockedFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SearchVector,
			&i.CoverPlaceholder,
			&i.FolderPath,
			&i.ExcludedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoriteIDs = `-- name: ListFavoriteIDs :many
SELECT comic_id FROM favorites WHERE user_id = $1
`

func (q *Queries) ListFavoriteIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listFavoriteIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var comic_id uuid.UUID
		if err := rows.Scan(&comic_id); err != nil {
			return nil, err
		}
		items = append(items, comic_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolderAccess = `-- name: ListFolderAccess :many
SELECT a.folder_id, a.user_id, a.can_write, u.username, u.display_name
FROM folder_access a
JOIN users u ON u.id = a.user_id
WHERE a.folder_id = $1
ORDER BY u.username
`

type ListFolderAccessRow struct {
	FolderID    uuid.UUID
	UserID      uuid.UUID
	CanWrite    bool
	Username    string
	DisplayName *string
}

func (q *Queries) ListFolderAccess(ctx context.Context, folderID uuid.UUID) ([]ListFolderAccessRow, error) {
	rows, err := q.db.Query(ctx, listFolderAccess, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFolderAccessRow{}
	for rows.Next() {
		var i ListFolderAccessRow
		if err := rows.Scan(
			&i.FolderID,
			&i.UserID,
			&i.CanWrite,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolders = `-- name: ListFolders :many

SELECT folder_path, count(*)::int AS comic_count
FROM comics
WHERE library_id = ANY($1::uuid[]) AND deleted_at IS NULL
GROUP BY folder_path
ORDER BY folder_path
`

type ListFoldersRow struct {
	FolderPath string
	ComicCount int32
}

// Outils de gestion : dossiers, favoris, notes, actions en lot.
// Arborescence des dossiers d'une bibliothèque.
//
// Les chemins distincts avec leur nombre d'albums ; le client en reconstitue
// l'arbre. Calculer l'arbre en SQL demanderait une récursion pour un résultat
// que le client sait bâtir en une passe.
func (q *Queries) ListFolders(ctx context.Context, libraryIds []uuid.UUID) ([]ListFoldersRow, error) {
	rows, err := q.db.Query(ctx, listFolders, libraryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFoldersRow{}
	for rows.Next() {
		var i ListFoldersRow
		if err := rows.Scan(&i.FolderPath, &i.ComicCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersByLibraries = `-- name: ListFoldersByLibraries :many

SELECT id, library_id, path, name, depth, parent_path, explicit, created_at, updated_at, read_only, access_code_hash FROM folders
WHERE library_id = ANY($1::uuid[])
ORDER BY library_id, path
`

// ─── Dossiers ────────────────────────────────────────────────────────────────
func (q *Queries) ListFoldersByLibraries(ctx context.Context, libraryIds []uuid.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByLibraries, libraryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Path,
			&i.Name,
			&i.Depth,
			&i.ParentPath,
			&i.Explicit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReadOnly,
			&i.AccessCodeHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLockedFolders = `-- name: ListLockedFolders :many
SELECT f.id, f.library_id, f.path, u.expires_at
FROM folders f
LEFT JOIN folder_unlocks u
       ON u.folder_id = f.id AND u.user_id = $1 AND u.expires_at > now()
WHERE f.library_id = ANY($2::uuid[])
  AND f.access_code_hash IS NOT NULL
ORDER BY f.path
`

type ListLockedFoldersParams struct {
	UserID     uuid.UUID
	LibraryIds []uuid.UUID
}

type ListLockedFoldersRow struct {
	ID        uuid.UUID
	LibraryID uuid.UUID
	Path      string
	ExpiresAt pgtype.Timestamptz
}

// Dossiers masqués d'une bibliothèque, avec l'échéance du déverrouillage
// éventuel accordé à ce compte.
//
// Une seule requête plutôt que deux : la liste des dossiers à code et celle des
// déverrouillages sont toujours consultées ensemble, et les séparer laisserait
// une fenêtre où l'une aurait changé sans l'autre.
func (q *Queries) ListLockedFolders(ctx context.Context, arg ListLockedFoldersParams) ([]ListLockedFoldersRow, error) {
	rows, err := q.db.Query(ctx, listLockedFolders, arg.UserID, arg.LibraryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLockedFoldersRow{}
	for rows.Next() {
		var i ListLockedFoldersRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Path,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatings = `-- name: ListRatings :many
SELECT comic_id, rating FROM comic_ratings WHERE user_id = $1
`

type ListRatingsRow struct {
	ComicID uuid.UUID
	Rating  int16
}

func (q *Queries) ListRatings(ctx context.Context, userID uuid.UUID) ([]ListRatingsRow, error) {
	rows, err := q.db.Query(ctx, listRatings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRatingsRow{}
	for rows.Next() {
		var i ListRatingsRow
		if err := rows.Scan(&i.ComicID, &i.Rating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestrictedFolders = `-- name: ListRestrictedFolders :many
SELECT f.path
FROM folders f
WHERE f.library_id = ANY($1::uuid[])
  AND EXISTS (SELECT 1 FROM folder_access a WHERE a.folder_id = f.id)
  AND NOT EXISTS (
      SELECT 1 FROM folder_access a
      WHERE a.folder_id = f.id AND a.user_id = $2
  )
ORDER BY f.path
`

type ListRestrictedFoldersParams struct {
	LibraryIds []uuid.UUID
	UserID     uuid.UUID
}

// Dossiers restreints qui ne sont PAS ouverts à ce compte.
//
// Même forme que la liste des dossiers masqués par un code : les deux produisent
// des chemins à retirer de la vue, et le catalogue les traite ensemble sans
// avoir à savoir lequel des deux mécanismes les a produits.
func (q *Queries) ListRestrictedFolders(ctx context.Context, arg ListRestrictedFoldersParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRestrictedFolders, arg.LibraryIds, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShareLinks = `-- name: ListShareLinks :many
SELECT id, token_hash, library_id, folder_path, comic_id, label, created_by, expires_at, revoked_at, last_used_at, use_count, created_at FROM share_links
WHERE library_id = ANY($1::uuid[])
  AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListShareLinks(ctx context.Context, libraryIds []uuid.UUID) ([]ShareLink, error) {
	rows, err := q.db.Query(ctx, listShareLinks, libraryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShareLink{}
	for rows.Next() {
		var i ShareLink
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.LibraryID,
			&i.FolderPath,
			&i.ComicID,
			&i.Label,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.UseCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedComics = `-- name: ListSharedComics :many
SELECT c.id, c.library_id, c.series_id, c.object_key, c.file_size, c.file_etag, c.content_hash, c.format, c.title, c.number, c.number_sort, c.volume, c.summary, c.released_at, c.age_rating, c.language, c.page_count, c.cover_page, c.state, c.state_detail, c.hydrated_at, c.indexed_at, c.metadata, c.locked_fields, c.created_at, c.updated_at, c.deleted_at, c.search_vector, c.cover_placeholder, c.folder_path, c.excluded_at, COALESCE(s.name, '')::text AS series_name
FROM comics c
LEFT JOIN series s ON s.id = c.series_id
WHERE c.library_id = $1
  AND c.deleted_at IS NULL
  AND c.excluded_at IS NULL
  AND c.state = 'ready'
  AND ($2::text = '' OR c.folder_path = $2::text OR c.folder_path LIKE $2::text || '/%')
ORDER BY c.folder_path, c.number_sort NULLS LAST, c.title
`

type ListSharedComicsParams struct {
	LibraryID uuid.UUID
	Path      string
}

type ListSharedComicsRow struct {
	Comic      Comic
	SeriesName string
}

// Albums accessibles par un lien de dossier.
func (q *Queries) ListSharedComics(ctx context.Context, arg ListSharedComicsParams) ([]ListSharedComicsRow, error) {
	rows, err := q.db.Query(ctx, listSharedComics, arg.LibraryID, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedComicsRow{}
	for rows.Next() {
		var i ListSharedComicsRow
		if err := rows.Scan(
			&i.Comic.ID,
			&i.Comic.LibraryID,
			&i.Comic.SeriesID,
			&i.Comic.ObjectKey,
			&i.Comic.FileSize,
			&i.Comic.FileEtag,
			&i.Comic.ContentHash,
			&i.Comic.Format,
			&i.Comic.Title,
			&i.Comic.Number,
			&i.Comic.NumberSort,
			&i.Comic.Volume,
			&i.Comic.Summary,
			&i.Comic.ReleasedAt,
			&i.Comic.AgeRating,
			&i.Comic.Language,
			&i.Comic.PageCount,
			&i.Comic.CoverPage,
			&i.Comic.State,
			&i.Comic.StateDetail,
			&i.Comic.HydratedAt,
			&i.Comic.IndexedAt,
			&i.Comic.Metadata,
			&i.Comic.LockedFields,
			&i.Comic.CreatedAt,
			&i.Comic.UpdatedAt,
			&i.Comic.DeletedAt,
			&i.Comic.SearchVector,
			&i.Comic.CoverPlaceholder,
			&i.Comic.FolderPath,
			&i.Comic.ExcludedAt,
			&i.SeriesName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFolderAgain = `-- name: LockFolderAgain :exec
DELETE FROM folder_unlocks WHERE user_id = $1 AND folder_id = $2
`

type LockFolderAgainParams struct {
	UserID   uuid.UUID
	FolderID uuid.UUID
}

func (q *Queries) LockFolderAgain(ctx context.Context, arg LockFolderAgainParams) error {
	_, err := q.db.Exec(ctx, lockFolderAgain, arg.UserID, arg.FolderID)
	return err
}

const moveComic = `-- name: MoveComic :exec
UPDATE comics
SET object_key  = $2,
    folder_path = $3
WHERE id = $1
`

type MoveComicParams struct {
	ID         uuid.UUID
	ObjectKey  string
	FolderPath string
}

func (q *Queries) MoveComic(ctx context.Context, arg MoveComicParams) error {
	_, err := q.db.Exec(ctx, moveComic, arg.ID, arg.ObjectKey, arg.FolderPath)
	return err
}

const pruneEmptyFolders = `-- name: PruneEmptyFolders :execrows
DELETE FROM folders f
WHERE f.library_id = $1
  AND f.explicit = false
  AND f.path <> ''
  AND NOT EXISTS (
      SELECT 1 FROM comics c
      WHERE c.library_id = f.library_id
        AND c.deleted_at IS NULL
        AND c.excluded_at IS NULL
        AND (c.folder_path = f.path OR c.folder_path LIKE f.path || '/%')
  )
  AND NOT EXISTS (
      SELECT 1 FROM folders child
      WHERE child.library_id = f.library_id
        AND child.explicit = true
        AND child.path LIKE f.path || '/%'
  )
`

// Supprime les dossiers constatés devenus vides.
//
// Seuls les non-explicites : un dossier créé à la main survit au fait d'être
// vide, c'est même souvent la raison de l'avoir créé.
func (q *Queries) PruneEmptyFolders(ctx context.Context, libraryID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, pruneEmptyFolders, libraryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeComic = `-- name: PurgeComic :exec
DELETE FROM comics WHERE id = $1
`

// Efface définitivement la ligne, une fois le fichier supprimé du backend.
func (q *Queries) PurgeComic(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, purgeComic, id)
	return err
}

const renameFolderTree = `-- name: RenameFolderTree :execrows
UPDATE folders
SET path = $2::text || substring(path FROM length($3::text) + 1),
    name = CASE
        WHEN path = $3::text THEN $4::text
        ELSE name
    END,
    depth = depth + $5::int,
    parent_path = CASE
        WHEN path = $3::text THEN $6::text
        ELSE $2::text || substring(parent_path FROM length($3::text) + 1)
    END
WHERE library_id = $1
  AND (path = $3::text OR path LIKE $3::text || '/%')
`

type RenameFolderTreeParams struct {
	LibraryID  uuid.UUID
	NewPath    string
	OldPath    string
	NewName    string
	DepthDelta int32
	NewParent  string
}

// Renomme une branche entière en une passe.
//
// Les chemins sont des chaînes : déplacer « Tintin » vers « BD/Tintin » revient
// à réécrire le préfixe de tous les descendants. Un parcours récursif
// d'identifiants ferait le même travail en n requêtes.
func (q *Queries) RenameFolderTree(ctx context.Context, arg RenameFolderTreeParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameFolderTree,
		arg.LibraryID,
		arg.NewPath,
		arg.OldPath,
		arg.NewName,
		arg.DepthDelta,
		arg.NewParent,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreComic = `-- name: RestoreComic :exec
UPDATE comics
SET deleted_at = NULL, excluded_at = NULL
WHERE id = $1
`

func (q *Queries) RestoreComic(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreComic, id)
	return err
}

const revokeFolderAccess = `-- name: RevokeFolderAccess :exec
DELETE FROM folder_access WHERE folder_id = $1 AND user_id = $2
`

type RevokeFolderAccessParams struct {
	FolderID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) RevokeFolderAccess(ctx context.Context, arg RevokeFolderAccessParams) error {
	_, err := q.db.Exec(ctx, revokeFolderAccess, arg.FolderID, arg.UserID)
	return err
}

const revokeFolderUnlocks = `-- name: RevokeFolderUnlocks :exec
DELETE FROM folder_unlocks WHERE folder_id = $1
`

// Retire tous les déverrouillages d'un dossier, quel que soit le compte.
//
// Appelé quand le code change ou disparaît : un déverrouillage obtenu avec
// l'ancien code ne doit pas survivre au nouveau.
func (q *Queries) RevokeFolderUnlocks(ctx context.Context, folderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeFolderUnlocks, folderID)
	return err
}

const revokeShareLink = `-- name: RevokeShareLink :execrows
UPDATE share_links SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeShareLink(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeShareLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setComicFolder = `-- name: SetComicFolder :exec
UPDATE comics SET folder_path = $2 WHERE id = $1
`

type SetComicFolderParams struct {
	ID         uuid.UUID
	FolderPath string
}

func (q *Queries) SetComicFolder(ctx context.Context, arg SetComicFolderParams) error {
	_, err := q.db.Exec(ctx, setComicFolder, arg.ID, arg.FolderPath)
	return err
}

const setFavorite = `-- name: SetFavorite :exec

INSERT INTO favorites (user_id, comic_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type SetFavoriteParams struct {
	UserID  uuid.UUID
	ComicID uuid.UUID
}

// ─── Favoris ─────────────────────────────────────────────────────────────────
func (q *Queries) SetFavorite(ctx context.Context, arg SetFavoriteParams) error {
	_, err := q.db.Exec(ctx, setFavorite, arg.UserID, arg.ComicID)
	return err
}

const setFolderAccessCode = `-- name: SetFolderAccessCode :one
UPDATE folders SET access_code_hash = $3 WHERE library_id = $1 AND path = $2 RETURNING id, library_id, path, name, depth, parent_path, explicit, created_at, updated_at, read_only, access_code_hash
`

type SetFolderAccessCodeParams struct {
	LibraryID      uuid.UUID
	Path           string
	AccessCodeHash *string
}

func (q *Queries) SetFolderAccessCode(ctx context.Context, arg SetFolderAccessCodeParams) (Folder, error) {
	row := q.db.QueryRow(ctx, setFolderAccessCode, arg.LibraryID, arg.Path, arg.AccessCodeHash)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Path,
		&i.Name,
		&i.Depth,
		&i.ParentPath,
		&i.Explicit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadOnly,
		&i.AccessCodeHash,
	)
	return i, err
}

const setFolderReadOnly = `-- name: SetFolderReadOnly :one

UPDATE folders SET read_only = $3 WHERE library_id = $1 AND path = $2 RETURNING id, library_id, path, name, depth, parent_path, explicit, created_at, updated_at, read_only, access_code_hash
`

type SetFolderReadOnlyParams struct {
	LibraryID uuid.UUID
	Path      string
	ReadOnly  bool
}

// ─── Verrous de dossiers ─────────────────────────────────────────────────────
func (q *Queries) SetFolderReadOnly(ctx context.Context, arg SetFolderReadOnlyParams) (Folder, error) {
	row := q.db.QueryRow(ctx, setFolderReadOnly, arg.LibraryID, arg.Path, arg.ReadOnly)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Path,
		&i.Name,
		&i.Depth,
		&i.ParentPath,
		&i.Explicit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadOnly,
		&i.AccessCodeHash,
	)
	return i, err
}

const setRating = `-- name: SetRating :exec

INSERT INTO comic_ratings (user_id, comic_id, rating)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, comic_id) DO UPDATE SET rating = EXCLUDED.rating
`

type SetRatingParams struct {
	UserID  uuid.UUID
	ComicID uuid.UUID
	Rating  int16
}

// ─── Notes ───────────────────────────────────────────────────────────────────
func (q *Queries) SetRating(ctx context.Context, arg SetRatingParams) error {
	_, err := q.db.Exec(ctx, setRating, arg.UserID, arg.ComicID, arg.Rating)
	return err
}

const touchShareLink = `-- name: TouchShareLink :exec
UPDATE share_links
SET last_used_at = now(), use_count = use_count + 1
WHERE id = $1
`

func (q *Queries) TouchShareLink(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchShareLink, id)
	return err
}

const treeHasAccessCode = `-- name: TreeHasAccessCode :one
SELECT EXISTS (
    SELECT 1 FROM folders
    WHERE library_id = $1
      AND access_code_hash IS NOT NULL
      AND ($2::text = path OR $2::text LIKE path || '/%')
) AS locked
`

type TreeHasAccessCodeParams struct {
	LibraryID uuid.UUID
	Path      string
}

// Un dossier porte-t-il un code d'accès, lui ou l'un de ses ancêtres ?
//
// Sert à refuser un lien public sur une branche masquée : les deux intentions se
// contredisent, et laisser les deux coexister reviendrait à publier ce qu'on
// vient de cacher.
func (q *Queries) TreeHasAccessCode(ctx context.Context, arg TreeHasAccessCodeParams) (bool, error) {
	row := q.db.QueryRow(ctx, treeHasAccessCode, arg.LibraryID, arg.Path)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}

const unlockFolder = `-- name: UnlockFolder :exec
INSERT INTO folder_unlocks (user_id, folder_id, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, folder_id) DO UPDATE SET expires_at = EXCLUDED.expires_at
`

type UnlockFolderParams struct {
	UserID    uuid.UUID
	FolderID  uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) UnlockFolder(ctx context.Context, arg UnlockFolderParams) error {
	_, err := q.db.Exec(ctx, unlockFolder, arg.UserID, arg.FolderID, arg.ExpiresAt)
	return err
}

const unsetFavorite = `-- name: UnsetFavorite :exec
DELETE FROM favorites WHERE user_id = $1 AND comic_id = $2
`

type UnsetFavoriteParams struct {
	UserID  uuid.UUID
	ComicID uuid.UUID
}

func (q *Queries) UnsetFavorite(ctx context.Context, arg UnsetFavoriteParams) error {
	_, err := q.db.Exec(ctx, unsetFavorite, arg.UserID, arg.ComicID)
	return err
}

const upsertFolder = `-- name: UpsertFolder :one
INSERT INTO folders (id, library_id, path, name, depth, parent_path, explicit)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (library_id, path) DO UPDATE
SET explicit = folders.explicit OR EXCLUDED.explicit
RETURNING id, library_id, path, name, depth, parent_path, explicit, created_at, updated_at, read_only, access_code_hash
`

type UpsertFolderParams struct {
	ID         uuid.UUID
	LibraryID  uuid.UUID
	Path       string
	Name       string
	Depth      int32
	ParentPath *string
	Explicit   bool
}

// Un dossier constaté par le parcours ne perd pas son caractère explicite :
// l'utilisateur l'a voulu, y déposer des fichiers ne défait pas sa décision.
func (q *Queries) UpsertFolder(ctx context.Context, arg UpsertFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, upsertFolder,
		arg.ID,
		arg.LibraryID,
		arg.Path,
		arg.Name,
		arg.Depth,
		arg.ParentPath,
		arg.Explicit,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Path,
		&i.Name,
		&i.Depth,
		&i.ParentPath,
		&i.Explicit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadOnly,
		&i.AccessCodeHash,
	)
	return i, err
}
