// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tools.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const bulkMarkRead = `-- name: BulkMarkRead :execrows

INSERT INTO reading_progress (user_id, comic_id, page, page_count, status, read_count, started_at, finished_at)
SELECT $1, c.id, greatest(c.page_count - 1, 0), c.page_count, 'read', 1, now(), now()
FROM comics c
WHERE c.id = ANY($2::uuid[])
ON CONFLICT (user_id, comic_id) DO UPDATE
SET page = excluded.page,
    page_count = excluded.page_count,
    status = 'read',
    read_count = reading_progress.read_count
        + CASE WHEN reading_progress.status <> 'read' THEN 1 ELSE 0 END,
    finished_at = coalesce(reading_progress.finished_at, now()),
    version = reading_progress.version + 1,
    updated_at = now()
`

type BulkMarkReadParams struct {
	UserID  uuid.UUID
	Column2 []uuid.UUID
}

// ─── Actions en lot ──────────────────────────────────────────────────────────
// Marque un lot d'albums comme lus.
//
// page est fixée à la dernière page de chaque album : marquer lu doit donner le
// même état que lire jusqu'au bout, sans quoi « reprendre la lecture »
// proposerait un album déjà déclaré terminé.
func (q *Queries) BulkMarkRead(ctx context.Context, arg BulkMarkReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkMarkRead, arg.UserID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkMarkUnread = `-- name: BulkMarkUnread :execrows
DELETE FROM reading_progress
WHERE user_id = $1 AND comic_id = ANY($2::uuid[])
`

type BulkMarkUnreadParams struct {
	UserID  uuid.UUID
	Column2 []uuid.UUID
}

func (q *Queries) BulkMarkUnread(ctx context.Context, arg BulkMarkUnreadParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkMarkUnread, arg.UserID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkSetFavorite = `-- name: BulkSetFavorite :execrows
INSERT INTO favorites (user_id, comic_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type BulkSetFavoriteParams struct {
	UserID  uuid.UUID
	Column2 []uuid.UUID
}

func (q *Queries) BulkSetFavorite(ctx context.Context, arg BulkSetFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkSetFavorite, arg.UserID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkUnsetFavorite = `-- name: BulkUnsetFavorite :execrows
DELETE FROM favorites WHERE user_id = $1 AND comic_id = ANY($2::uuid[])
`

type BulkUnsetFavoriteParams struct {
	UserID  uuid.UUID
	Column2 []uuid.UUID
}

func (q *Queries) BulkUnsetFavorite(ctx context.Context, arg BulkUnsetFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkUnsetFavorite, arg.UserID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearRating = `-- name: ClearRating :exec
DELETE FROM comic_ratings WHERE user_id = $1 AND comic_id = $2
`

type ClearRatingParams struct {
	UserID  uuid.UUID
	ComicID uuid.UUID
}

func (q *Queries) ClearRating(ctx context.Context, arg ClearRatingParams) error {
	_, err := q.db.Exec(ctx, clearRating, arg.UserID, arg.ComicID)
	return err
}

const editComic = `-- name: EditComic :one

UPDATE comics
SET title       = coalesce($1, title),
    number      = coalesce($2, number),
    summary     = coalesce($3, summary),
    language    = coalesce($4, language),
    locked_fields = (
        SELECT array_agg(DISTINCT f) FROM unnest(
            locked_fields || $5::text[]
        ) AS f
    )
WHERE id = $6
RETURNING id, library_id, series_id, object_key, file_size, file_etag, content_hash, format, title, number, number_sort, volume, summary, released_at, age_rating, language, page_count, cover_page, state, state_detail, hydrated_at, indexed_at, metadata, locked_fields, created_at, updated_at, deleted_at, search_vector, cover_placeholder, folder_path
`

type EditComicParams struct {
	Title       *string
	Number      *string
	Summary     *string
	Language    *string
	NewlyLocked []string
	ID          uuid.UUID
}

// ─── Édition manuelle ────────────────────────────────────────────────────────
// Édition d'un album par l'utilisateur.
//
// Chaque champ renseigné entre dans locked_fields : une réindexation ne doit
// jamais écraser une saisie manuelle. C'est la contrepartie de l'automatisme —
// sans elle, corriger un titre serait inutile.
func (q *Queries) EditComic(ctx context.Context, arg EditComicParams) (Comic, error) {
	row := q.db.QueryRow(ctx, editComic,
		arg.Title,
		arg.Number,
		arg.Summary,
		arg.Language,
		arg.NewlyLocked,
		arg.ID,
	)
	var i Comic
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.SeriesID,
		&i.ObjectKey,
		&i.FileSize,
		&i.FileEtag,
		&i.ContentHash,
		&i.Format,
		&i.Title,
		&i.Number,
		&i.NumberSort,
		&i.Volume,
		&i.Summary,
		&i.ReleasedAt,
		&i.AgeRating,
		&i.Language,
		&i.PageCount,
		&i.CoverPage,
		&i.State,
		&i.StateDetail,
		&i.HydratedAt,
		&i.IndexedAt,
		&i.Metadata,
		&i.LockedFields,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SearchVector,
		&i.CoverPlaceholder,
		&i.FolderPath,
	)
	return i, err
}

const listFavoriteIDs = `-- name: ListFavoriteIDs :many
SELECT comic_id FROM favorites WHERE user_id = $1
`

func (q *Queries) ListFavoriteIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listFavoriteIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var comic_id uuid.UUID
		if err := rows.Scan(&comic_id); err != nil {
			return nil, err
		}
		items = append(items, comic_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolders = `-- name: ListFolders :many

SELECT folder_path, count(*)::int AS comic_count
FROM comics
WHERE library_id = ANY($1::uuid[]) AND deleted_at IS NULL
GROUP BY folder_path
ORDER BY folder_path
`

type ListFoldersRow struct {
	FolderPath string
	ComicCount int32
}

// Outils de gestion : dossiers, favoris, notes, actions en lot.
// Arborescence des dossiers d'une bibliothèque.
//
// Les chemins distincts avec leur nombre d'albums ; le client en reconstitue
// l'arbre. Calculer l'arbre en SQL demanderait une récursion pour un résultat
// que le client sait bâtir en une passe.
func (q *Queries) ListFolders(ctx context.Context, libraryIds []uuid.UUID) ([]ListFoldersRow, error) {
	rows, err := q.db.Query(ctx, listFolders, libraryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFoldersRow{}
	for rows.Next() {
		var i ListFoldersRow
		if err := rows.Scan(&i.FolderPath, &i.ComicCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatings = `-- name: ListRatings :many
SELECT comic_id, rating FROM comic_ratings WHERE user_id = $1
`

type ListRatingsRow struct {
	ComicID uuid.UUID
	Rating  int16
}

func (q *Queries) ListRatings(ctx context.Context, userID uuid.UUID) ([]ListRatingsRow, error) {
	rows, err := q.db.Query(ctx, listRatings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRatingsRow{}
	for rows.Next() {
		var i ListRatingsRow
		if err := rows.Scan(&i.ComicID, &i.Rating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setComicFolder = `-- name: SetComicFolder :exec
UPDATE comics SET folder_path = $2 WHERE id = $1
`

type SetComicFolderParams struct {
	ID         uuid.UUID
	FolderPath string
}

func (q *Queries) SetComicFolder(ctx context.Context, arg SetComicFolderParams) error {
	_, err := q.db.Exec(ctx, setComicFolder, arg.ID, arg.FolderPath)
	return err
}

const setFavorite = `-- name: SetFavorite :exec

INSERT INTO favorites (user_id, comic_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type SetFavoriteParams struct {
	UserID  uuid.UUID
	ComicID uuid.UUID
}

// ─── Favoris ─────────────────────────────────────────────────────────────────
func (q *Queries) SetFavorite(ctx context.Context, arg SetFavoriteParams) error {
	_, err := q.db.Exec(ctx, setFavorite, arg.UserID, arg.ComicID)
	return err
}

const setRating = `-- name: SetRating :exec

INSERT INTO comic_ratings (user_id, comic_id, rating)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, comic_id) DO UPDATE SET rating = EXCLUDED.rating
`

type SetRatingParams struct {
	UserID  uuid.UUID
	ComicID uuid.UUID
	Rating  int16
}

// ─── Notes ───────────────────────────────────────────────────────────────────
func (q *Queries) SetRating(ctx context.Context, arg SetRatingParams) error {
	_, err := q.db.Exec(ctx, setRating, arg.UserID, arg.ComicID, arg.Rating)
	return err
}

const unsetFavorite = `-- name: UnsetFavorite :exec
DELETE FROM favorites WHERE user_id = $1 AND comic_id = $2
`

type UnsetFavoriteParams struct {
	UserID  uuid.UUID
	ComicID uuid.UUID
}

func (q *Queries) UnsetFavorite(ctx context.Context, arg UnsetFavoriteParams) error {
	_, err := q.db.Exec(ctx, unsetFavorite, arg.UserID, arg.ComicID)
	return err
}
