// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const canAccessLibrary = `-- name: CanAccessLibrary :one
SELECT
    $2::boolean
    OR NOT EXISTS (SELECT 1 FROM library_access a WHERE a.library_id = $3)
    OR EXISTS (SELECT 1 FROM library_access a WHERE a.library_id = $3 AND a.user_id = $1)
    AS allowed
`

type CanAccessLibraryParams struct {
	UserID    uuid.UUID
	Column2   bool
	LibraryID uuid.UUID
}

func (q *Queries) CanAccessLibrary(ctx context.Context, arg CanAccessLibraryParams) (*bool, error) {
	row := q.db.QueryRow(ctx, canAccessLibrary, arg.UserID, arg.Column2, arg.LibraryID)
	var allowed *bool
	err := row.Scan(&allowed)
	return allowed, err
}

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM users WHERE role = 'admin' AND deleted_at IS NULL
`

// Compte les administrateurs encore actifs.
//
// Sert à empêcher la suppression ou la rétrogradation du dernier d'entre eux :
// une instance sans administrateur ne peut plus être administrée du tout, et
// rien dans l'interface ne permettrait d'en refaire un.
func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users WHERE deleted_at IS NULL
`

// Sert à l'assistant de première installation : tant qu'il n'y a personne,
// l'inscription du premier administrateur est ouverte.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (id, user_id, device_id, token_hash, parent_id, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, device_id, token_hash, parent_id, expires_at, revoked_at, user_agent, ip, created_at
`

type CreateSessionParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	DeviceID  uuid.NullUUID
	TokenHash []byte
	ParentID  uuid.NullUUID
	ExpiresAt pgtype.Timestamptz
	UserAgent *string
	IP        *netip.Addr
}

// ─── Sessions ────────────────────────────────────────────────────────────────
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.TokenHash,
		arg.ParentID,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IP,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.ParentID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IP,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, password_hash, role, display_name)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, email, password_hash, role, display_name, avatar_key, restricted, max_age_rating, preferences, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID           uuid.UUID
	Username     string
	Email        *string
	PasswordHash string
	Role         UserRole
	DisplayName  *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.AvatarKey,
		&i.Restricted,
		&i.MaxAgeRating,
		&i.Preferences,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = $1 AND user_id = $2
`

type DeleteDeviceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.Exec(ctx, deleteDevice, arg.ID, arg.UserID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < now() - interval '30 days'
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDevice = `-- name: GetDevice :one
SELECT id, user_id, name, platform, app_version, push_token, last_seen_at, created_at FROM devices WHERE id = $1
`

func (q *Queries) GetDevice(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Platform,
		&i.AppVersion,
		&i.PushToken,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, device_id, token_hash, parent_id, expires_at, revoked_at, user_agent, ip, created_at FROM sessions WHERE token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.ParentID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IP,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, password_hash, role, display_name, avatar_key, restricted, max_age_rating, preferences, last_login_at, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.AvatarKey,
		&i.Restricted,
		&i.MaxAgeRating,
		&i.Preferences,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, role, display_name, avatar_key, restricted, max_age_rating, preferences, last_login_at, created_at, updated_at, deleted_at FROM users WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.AvatarKey,
		&i.Restricted,
		&i.MaxAgeRating,
		&i.Preferences,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const grantLibraryAccess = `-- name: GrantLibraryAccess :exec
INSERT INTO library_access (library_id, user_id, can_write)
VALUES ($1, $2, $3)
ON CONFLICT (library_id, user_id) DO UPDATE SET can_write = EXCLUDED.can_write
`

type GrantLibraryAccessParams struct {
	LibraryID uuid.UUID
	UserID    uuid.UUID
	CanWrite  bool
}

func (q *Queries) GrantLibraryAccess(ctx context.Context, arg GrantLibraryAccessParams) error {
	_, err := q.db.Exec(ctx, grantLibraryAccess, arg.LibraryID, arg.UserID, arg.CanWrite)
	return err
}

const listAccessByUser = `-- name: ListAccessByUser :many
SELECT library_id, user_id, can_write FROM library_access WHERE user_id = $1
`

func (q *Queries) ListAccessByUser(ctx context.Context, userID uuid.UUID) ([]LibraryAccess, error) {
	rows, err := q.db.Query(ctx, listAccessByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryAccess{}
	for rows.Next() {
		var i LibraryAccess
		if err := rows.Scan(&i.LibraryID, &i.UserID, &i.CanWrite); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, user_id, name, platform, app_version, push_token, last_seen_at, created_at FROM devices WHERE user_id = $1 ORDER BY last_seen_at DESC
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userID uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Platform,
			&i.AppVersion,
			&i.PushToken,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryAccess = `-- name: ListLibraryAccess :many
SELECT library_id, user_id, can_write FROM library_access WHERE library_id = $1
`

func (q *Queries) ListLibraryAccess(ctx context.Context, libraryID uuid.UUID) ([]LibraryAccess, error) {
	rows, err := q.db.Query(ctx, listLibraryAccess, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryAccess{}
	for rows.Next() {
		var i LibraryAccess
		if err := rows.Scan(&i.LibraryID, &i.UserID, &i.CanWrite); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, role, display_name, avatar_key, restricted, max_age_rating, preferences, last_login_at, created_at, updated_at, deleted_at FROM users WHERE deleted_at IS NULL ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.DisplayName,
			&i.AvatarKey,
			&i.Restricted,
			&i.MaxAgeRating,
			&i.Preferences,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleLibraries = `-- name: ListVisibleLibraries :many

SELECT l.id, l.storage_backend_id, l.name, l.kind, l.root_prefix, l.scan_options, l.scan_cron, l.last_scan_at, l.last_scan_status, l.comic_count, l.created_at, l.updated_at FROM libraries l
WHERE $2::boolean = true
   OR NOT EXISTS (SELECT 1 FROM library_access a WHERE a.library_id = l.id)
   OR EXISTS (SELECT 1 FROM library_access a WHERE a.library_id = l.id AND a.user_id = $1)
ORDER BY l.name
`

type ListVisibleLibrariesParams struct {
	UserID  uuid.UUID
	Column2 bool
}

// ─── Accès aux bibliothèques ─────────────────────────────────────────────────
// Bibliothèques visibles par un utilisateur.
//
// Règle : une bibliothèque sans aucune restriction est visible de tous ; dès
// qu'une restriction existe, seuls les utilisateurs listés y ont accès. Les
// administrateurs voient tout.
func (q *Queries) ListVisibleLibraries(ctx context.Context, arg ListVisibleLibrariesParams) ([]Library, error) {
	rows, err := q.db.Query(ctx, listVisibleLibraries, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Library{}
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.StorageBackendID,
			&i.Name,
			&i.Kind,
			&i.RootPrefix,
			&i.ScanOptions,
			&i.ScanCron,
			&i.LastScanAt,
			&i.LastScanStatus,
			&i.ComicCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :execrows
UPDATE sessions SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeLibraryAccess = `-- name: RevokeLibraryAccess :exec
DELETE FROM library_access WHERE library_id = $1 AND user_id = $2
`

type RevokeLibraryAccessParams struct {
	LibraryID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RevokeLibraryAccess(ctx context.Context, arg RevokeLibraryAccessParams) error {
	_, err := q.db.Exec(ctx, revokeLibraryAccess, arg.LibraryID, arg.UserID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionChain = `-- name: RevokeSessionChain :execrows
WITH RECURSIVE chain AS (
    SELECT s.id FROM sessions s WHERE s.id = $1
    UNION
    SELECT s.id FROM sessions s JOIN chain c ON s.parent_id = c.id
)
UPDATE sessions
SET revoked_at = now()
WHERE sessions.id IN (SELECT chain.id FROM chain)
  AND sessions.revoked_at IS NULL
`

// Détection de réutilisation : si un jeton déjà tourné est présenté, c'est
// qu'il a été volé. On révoque alors toute la chaîne de rotation, pas
// seulement le jeton présenté.
func (q *Queries) RevokeSessionChain(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionChain, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const setUserRestriction = `-- name: SetUserRestriction :one

UPDATE users
SET restricted     = $2,
    max_age_rating = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, username, email, password_hash, role, display_name, avatar_key, restricted, max_age_rating, preferences, last_login_at, created_at, updated_at, deleted_at
`

type SetUserRestrictionParams struct {
	ID           uuid.UUID
	Restricted   bool
	MaxAgeRating *int16
}

// ─── Administration des comptes ──────────────────────────────────────────────
func (q *Queries) SetUserRestriction(ctx context.Context, arg SetUserRestrictionParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserRestriction, arg.ID, arg.Restricted, arg.MaxAgeRating)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.AvatarKey,
		&i.Restricted,
		&i.MaxAgeRating,
		&i.Preferences,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users SET role = $2 WHERE id = $1
`

type SetUserRoleParams struct {
	ID   uuid.UUID
	Role UserRole
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.Exec(ctx, setUserRole, arg.ID, arg.Role)
	return err
}

const setUserRoleReturning = `-- name: SetUserRoleReturning :one
UPDATE users SET role = $2 WHERE id = $1 AND deleted_at IS NULL RETURNING id, username, email, password_hash, role, display_name, avatar_key, restricted, max_age_rating, preferences, last_login_at, created_at, updated_at, deleted_at
`

type SetUserRoleReturningParams struct {
	ID   uuid.UUID
	Role UserRole
}

func (q *Queries) SetUserRoleReturning(ctx context.Context, arg SetUserRoleReturningParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserRoleReturning, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.AvatarKey,
		&i.Restricted,
		&i.MaxAgeRating,
		&i.Preferences,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE devices SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchDevice, id)
	return err
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) TouchUserLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLogin, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = coalesce($2, display_name),
    email        = coalesce($3, email),
    preferences  = coalesce($4, preferences)
WHERE id = $1
RETURNING id, username, email, password_hash, role, display_name, avatar_key, restricted, max_age_rating, preferences, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID
	DisplayName *string
	Email       *string
	Preferences []byte
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.Preferences,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.AvatarKey,
		&i.Restricted,
		&i.MaxAgeRating,
		&i.Preferences,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertDevice = `-- name: UpsertDevice :one

INSERT INTO devices (id, user_id, name, platform, app_version)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
SET name         = EXCLUDED.name,
    app_version  = EXCLUDED.app_version,
    last_seen_at = now()
RETURNING id, user_id, name, platform, app_version, push_token, last_seen_at, created_at
`

type UpsertDeviceParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Platform   DevicePlatform
	AppVersion *string
}

// ─── Appareils ───────────────────────────────────────────────────────────────
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Platform,
		arg.AppVersion,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Platform,
		&i.AppVersion,
		&i.PushToken,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}
